### ISSUE TITLE
Image editing

### ISSUE THREAD

**Issue by ThatOneCalculator** [IacobIonut01/Gallery#1]
Possibly with https://github.com/burhanrashid52/PhotoEditor ?

**Comment by Nogooduser** [comment]
I'd like to add, if possible, the app should allow you to select which editor you want to use when you press the edit button.

Some people (like myself) always edit files with a separate app, so it's very convenient when a gallery app allows us to choose.

**Comment by T8RIN** [comment]
Have you tried [ImageToolbox](GitHub.com/t8rin/ImageToolbox) ? 👀

**Comment by IacobIonut01** [comment]
> Have you tried [ImageToolbox](https://github.com/T8RIN/ImageToolbox) ? 👀

Yes, but the Image editor needed for a Gallery app must be much more UX focused, that's why is takes quite a bit to come up with everything

**Comment by T8RIN** [comment]
> > Have you tried [ImageToolbox](https://github.com/T8RIN/ImageToolbox) ? 👀
> 
> Yes, but the Image editor needed for a Gallery app must be much more UX focused, that's why is takes quite a bit to come up with everything
> 
> But I might include some parts of it (with the proper authorship) if necessary

I'm trying to create a really understandable app, maybe you also have some suggestions to make it better :)

**Comment by fallsdevil** [comment]
> I'd like to add, if possible, the app ideally would allow you to select which editor you want to use when you press the edit button.
> 
> Some people (like myself) always edit files with a separate app, so it's very convenient when a gallery app allows us to choose.

Yes, I would really like it to be all in one, but I understand that this takes time, so it would be nice if there was the option to select a default app when you click on "edit" to always open it without asking.

**Comment by T8RIN** [comment]
> > I'd like to add, if possible, the app ideally would allow you to select which editor you want to use when you press the edit button.
> > 
> > Some people (like myself) always edit files with a separate app, so it's very convenient when a gallery app allows us to choose.
> 
> Yes, I would really like it to be all in one, but I understand that this takes time, so it would be nice if there was the option to select a default app when you click on "edit" to always open it without asking.

[ImageToolbox](GitHub.com/T8RIn/ImageToolbox)😁

**Comment by Zaxx69** [comment]
Bro will the photo editing be added?

**Comment by IacobIonut01** [comment]
Yes bro.

**Comment by bhairavshankara** [comment]
> > > Have you tried [ImageToolbox](https://github.com/T8RIN/ImageToolbox) ? 👀
> > 
> > 
> > Yes, but the Image editor needed for a Gallery app must be much more UX focused, that's why is takes quite a bit to come up with everything
> > But I might include some parts of it (with the proper authorship) if necessary
> 
> I'm trying to create a really understandable app, maybe you also have some suggestions to make it better :)

Hi TR8IN, I have been using image toolbox for a long time 
My overall suggestion is to make the apps clutter free
The app almost feels like an alternative to SnapSeed with its advanced editing tools and options but with more cluttery ui
In simple words the ui is something that is extremely different compared to other apps maybe you have designed   it based on your workflow.
And I don't think that's what an "gallery" focuser editor should be, rather basic features like crop, rotate, draw, flip, blur, is more than enough.
Also to note whenever I want to edit in image toolbox I launch toolbox first and then edit rather than going from the gallery, for simple edits I usually use Google Photos as its ui/ux is much more minimal and consistent with rest of android compared to toolbox.
Anways great app continue the great work!!!
But don't try to make it as an app for basic edits - I would say go with the snapseed route and cram all the options you can !!!

**Comment by T8RIN** [comment]
> > > > Have you tried [ImageToolbox](https://github.com/T8RIN/ImageToolbox) ? 👀
> > > 
> > > 
> > > Yes, but the Image editor needed for a Gallery app must be much more UX focused, that's why is takes quite a bit to come up with everything
> > > But I might include some parts of it (with the proper authorship) if necessary
> > 
> > I'm trying to create a really understandable app, maybe you also have some suggestions to make it better :)
> 
> Hi TR8IN, I have been using image toolbox for a long time 
> My overall suggestion is to make the apps clutter free
> The app almost feels like an alternative to SnapSeed with its advanced editing tools and options but with more cluttery ui
> In simple words the ui is something that is extremely different compared to other apps maybe you have designed   it based on your workflow.
> And I don't think that's what an "gallery" focuser editor should be, rather basic features like crop, rotate, draw, flip, blur, is more than enough.
> Also to note whenever I want to edit in image toolbox I launch toolbox first and then edit rather than going from the gallery, for simple edits I usually use Google Photos as its ui/ux is much more minimal and consistent with rest of android compared to toolbox.
> Anways great app continue the great work!!!
> But don't try to make it as an app for basic edits - I would say go with the snapseed route and cram all the options you can !!!

I recently added single edit mode, it has some base features in one place🐸

**Comment by heckarman** [comment]
SimpleMobileTools Advanced editor is good. It would be worth looking into..

**Comment by Cwpute** [comment]
While i agree that rotating pictures is a must for gallery apps, i'm not sure other editing tools might ée so nuch needed.
I can understand the case of the crop tool, for screenshots specifically, but even this tool car be provided by a dedicated app.

There are already several standalone apps using the PhotoEditor library which are good enough for what they do (no much, mind you), there is the Litrato app which showed premise but hasn't seen updates since 2 years now. Finally there is Pocket Paint, but this one is probably way overkill for quick image editing that-most of you want to do through Gallery.

My point is, i hope this doesn't turn into feature bloat later on. Maybe we should support existing apps instead.

**Comment by AlphaElwedritsch** [comment]
> > > > > Have you tried [ImageToolbox](https://github.com/T8RIN/ImageToolbox) ? 👀
> > > > 
> > > > 
> > > > Yes, but the Image editor needed for a Gallery app must be much more UX focused, that's why is takes quite a bit to come up with everything
> > > > But I might include some parts of it (with the proper authorship) if necessary
> > > 
> > > 
> > > I'm trying to create a really understandable app, maybe you also have some suggestions to make it better :)
> > 
> > 
> > Hi TR8IN, I have been using image toolbox for a long time
> > My overall suggestion is to make the apps clutter free
> > The app almost feels like an alternative to SnapSeed with its advanced editing tools and options but with more cluttery ui
> > In simple words the ui is something that is extremely different compared to other apps maybe you have designed   it based on your workflow.
> > And I don't think that's what an "gallery" focuser editor should be, rather basic features like crop, rotate, draw, flip, blur, is more than enough.
> > Also to note whenever I want to edit in image toolbox I launch toolbox first and then edit rather than going from the gallery, for simple edits I usually use Google Photos as its ui/ux is much more minimal and consistent with rest of android compared to toolbox.
> > Anways great app continue the great work!!!
> > But don't try to make it as an app for basic edits - I would say go with the snapseed route and cram all the options you can !!!
> 
> I recently added single edit mode, it has some base features in one place🐸

Where?
In the app?

**Comment by T8RIN** [comment]
> > > > > > Have you tried [ImageToolbox](https://github.com/T8RIN/ImageToolbox) ? 👀
> > > > > 
> > > > > 
> > > > > Yes, but the Image editor needed for a Gallery app must be much more UX focused, that's why is takes quite a bit to come up with everything
> > > > > But I might include some parts of it (with the proper authorship) if necessary
> > > > 
> > > > 
> > > > I'm trying to create a really understandable app, maybe you also have some suggestions to make it better :)
> > > 
> > > 
> > > Hi TR8IN, I have been using image toolbox for a long time
> > > My overall suggestion is to make the apps clutter free
> > > The app almost feels like an alternative to SnapSeed with its advanced editing tools and options but with more cluttery ui
> > > In simple words the ui is something that is extremely different compared to other apps maybe you have designed   it based on your workflow.
> > > And I don't think that's what an "gallery" focuser editor should be, rather basic features like crop, rotate, draw, flip, blur, is more than enough.
> > > Also to note whenever I want to edit in image toolbox I launch toolbox first and then edit rather than going from the gallery, for simple edits I usually use Google Photos as its ui/ux is much more minimal and consistent with rest of android compared to toolbox.
> > > Anways great app continue the great work!!!
> > > But don't try to make it as an app for basic edits - I would say go with the snapseed route and cram all the options you can !!!
> > 
> > I recently added single edit mode, it has some base features in one place🐸
> 
> Where?
> In the app?

Yup, this is the first option with the pencil

**Comment by AlphaElwedritsch** [comment]
> > > > > > > Have you tried [ImageToolbox](https://github.com/T8RIN/ImageToolbox) ? 👀
> > > > > > 
> > > > > > 
> > > > > > Yes, but the Image editor needed for a Gallery app must be much more UX focused, that's why is takes quite a bit to come up with everything
> > > > > > But I might include some parts of it (with the proper authorship) if necessary
> > > > > 
> > > > > 
> > > > > I'm trying to create a really understandable app, maybe you also have some suggestions to make it better :)
> > > > 
> > > > 
> > > > Hi TR8IN, I have been using image toolbox for a long time
> > > > My overall suggestion is to make the apps clutter free
> > > > The app almost feels like an alternative to SnapSeed with its advanced editing tools and options but with more cluttery ui
> > > > In simple words the ui is something that is extremely different compared to other apps maybe you have designed   it based on your workflow.
> > > > And I don't think that's what an "gallery" focuser editor should be, rather basic features like crop, rotate, draw, flip, blur, is more than enough.
> > > > Also to note whenever I want to edit in image toolbox I launch toolbox first and then edit rather than going from the gallery, for simple edits I usually use Google Photos as its ui/ux is much more minimal and consistent with rest of android compared to toolbox.
> > > > Anways great app continue the great work!!!
> > > > But don't try to make it as an app for basic edits - I would say go with the snapseed route and cram all the options you can !!!
> > > 
> > > 
> > > I recently added single edit mode, it has some base features in one place🐸
> > 
> > 
> > Where?
> > In the app?
> 
> Yup, this is the first option with the pencil

OK, but if I press the pencil, I get the info that there is no app.
Latest github version nomap

**Comment by T8RIN** [comment]
I'm ImageToolbox developer, not gallery, but i mean this one ![Screenshot_20231202-220612_Image Toolbox (Resizer).png](https://github.com/IacobIonut01/Gallery/assets/52178347/13ad15e1-1f3c-41d4-89b6-49892ec33466)

![Screenshot_20231202-220620_Image Toolbox (Resizer).png](https://github.com/IacobIonut01/Gallery/assets/52178347/9da2f34e-faea-4a91-af72-f6c06993ebf4)

**Comment by AlphaElwedritsch** [comment]
> I'm ImageToolbox developer, not gallery, but i mean this one ![Screenshot_20231202-220612_Image Toolbox (Resizer).png](https://private-user-images.githubusercontent.com/52178347/287469562-13ad15e1-1f3c-41d4-89b6-49892ec33466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NDQ0ODMsIm5iZiI6MTcwMTU0NDE4MywicGF0aCI6Ii81MjE3ODM0Ny8yODc0Njk1NjItMTNhZDE1ZTEtMWYzYy00MWQ0LTg5YjYtNDk4OTJlYzMzNDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE5MDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMDc4MmRkOWM0YmI0NTc2MDkxNzI1M2ZmNTQ3NjFiOTk5NzUzZjgxNzJiZmJhZDNlZDAyODIzYzhiYWJkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MhLK7gTj5D51f29XDsX-nAT0eN96n78fNnXDUgbhhwY)
> 
> ![Screenshot_20231202-220620_Image Toolbox (Resizer).png](https://private-user-images.githubusercontent.com/52178347/287469563-9da2f34e-faea-4a91-af72-f6c06993ebf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NDQ0ODMsIm5iZiI6MTcwMTU0NDE4MywicGF0aCI6Ii81MjE3ODM0Ny8yODc0Njk1NjMtOWRhMmYzNGUtZmFlYS00YTkxLWFmNzItZjZjMDY5OTNlYmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE5MDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYTc3YTQ0ZTAyMjkxOWM1YWIyYWUzNDkyZmExYzZiMTcxNGVjNmY3MWU3NjJkMmM1MDdlNGE3YTBmZGIyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gkdQ4bk9fsMyYffgvV1TcIHWqxyzW1mrunmUP59ZPKo)

Ah, OK, sorry

**Comment by IacobIonut01** [comment]
In Progress
9a0e2171898e1c333ec6bae31f9dbffb6a7b778e
faf88d3d46dcc9fcaa2cc342273ea8e267a6bd8b
5ac7ec8d1812cd4d533818aefc4f20d087e8a8e4

**Comment by wefalltomorrow** [comment]
Is video editing also planned?

**Comment by IacobIonut01** [comment]
Yes
