### ISSUE TITLE
Landscape/portrait switch button 

### ISSUE THREAD

**Issue by serrq** [IacobIonut01/Gallery#10]
I don't want activate the orientation sensor.
Might you add a orientation switch button in GUI?

![1000006718](https://user-images.githubusercontent.com/113377431/231152233-9d1b99c3-6c36-4a34-838c-a1204ad612c6.jpg)

**Comment by IacobIonut01** [comment]
Thanks for the suggestion. I will make sure it will be included by 1.1 Release
