### ISSUE TITLE
Title below Icons in imageview is cropped

### ISSUE THREAD

**Issue by laraib07** [IacobIonut01/Gallery#109]
Title below icons in imageview is cropped . Here is the screenshot:
![Screenshot_20230714-201423_Gallery](https://github.com/IacobIonut01/Gallery/assets/25507825/8d247d77-a46f-4b91-b445-179b078d6de5)

**Comment by IacobIonut01** [comment]
It's already fixed, try the latest build from the "Actions" tab, check for artifacts and download the zip

**Comment by laraib07** [comment]
I am using v1.1.0 from fdroid. Is it different?

**Comment by IacobIonut01** [comment]
> I am using v1.1.0 from fdroid. Is it different?
> 

Yes, the one from the "Actions" tab is updated every change.

**Comment by laraib07** [comment]
Found it and installed successfully. Thanks!
