### ISSUE TITLE
Swipe up for image info

### ISSUE THREAD

**Issue by mon-jai** [IacobIonut01/Gallery#114]
It will be more intuitive if we could open the image info panel by swiping up  (instead of clicking the info button).

https://github.com/IacobIonut01/Gallery/assets/91261297/1cc8639c-86af-4140-8398-81e1f782a788

**Comment by IacobIonut01** [comment]
Yeah, I'm still working on a better UI for the Media View and I've considered adding this kind of gesture.


Thanks for the request

**Comment by mon-jai** [comment]
@IacobIonut01 Seems that the feature is missing again in v3.0.1

**Comment by IacobIonut01** [comment]
> @IacobIonut01 Seems that the feature is missing again in v3.0.1

Swipe from the lower part, where the buttons are

**Comment by mon-jai** [comment]
@IacobIonut01 Would it be possible to make it work across the entire screen as well? That would make the feature more discoverable.
