### ISSUE TITLE
[Suggession/Enhancement] Hide search bar when scrolling in home screen.

### ISSUE THREAD

**Issue by SweetD3v** [IacobIonut01/Gallery#124]
This is a nice and clean gallery app! Apart from some performance issues. (which is great in release version, maybe that's just debug version issue I think)
But rather than that, It would be great if you animate and hide the search bar when scrolling in  home screen. Currently it stays there and it doesn't look neat.

**Comment by IacobIonut01** [comment]
Hi, Compose doesn't fully perform in debug versions, so that's why it's best to test/use the app in release flavor.

Great enhancement, I'll add it asap

**Comment by SweetD3v** [comment]
> Hi, Compose doesn't fully perform in debug versions, so that's why it's best to test/use the app in release flavor.
> 
> Great enhancement, I'll add it asap

Glad you added it! Keep up the good work. :)
