### ISSUE TITLE
UI not scaling correct on bigger devices

### ISSUE THREAD

**Issue by robin-161** [IacobIonut01/Gallery#126]
The "interaction bar" does not scale right on bigger devices. It's fine on an Google Pixel 5 but on my Pixel 6 it looks off like this:
<img alt="" src="https://github.com/IacobIonut01/Gallery/assets/114015901/3bc4ed48-63c7-4c2a-a308-0584b54f135b" width="200">

**Comment by IacobIonut01** [comment]
The new design coming will be limited to only 4 options in the main page, everything else will be moved inside Media Info Sheet (with a swipe from the bottom)
