### ISSUE TITLE
(Bug) Weird sticky header

### ISSUE THREAD

**Issue by T8RIN** [IacobIonut01/Gallery#134]
![Screenshot_20230813-135627_Pixel Launcher.png](https://github.com/IacobIonut01/Gallery/assets/52178347/a19d86cf-f258-4d54-9a04-50c046edda97)

This one is definitely extra, and really annoying :(

**Comment by IacobIonut01** [comment]
It suddenly started happening with some devices, I'm still looking into that. Thanks

**Comment by T8RIN** [comment]
Maybe I will be able to help later

**Comment by IacobIonut01** [comment]
@T8RIN check with the apk after Github Action completes

**Comment by T8RIN** [comment]
Okay, thanks!

**Comment by T8RIN** [comment]
Checked, issue persists
