### ISSUE TITLE
Deleting the photo from the app causes the app to stop working 

### ISSUE THREAD

**Issue by zoroya1** [IacobIonut01/Gallery#135]
Whenever I try to delete a photo from the gallery app (from that single photo view), the gallery app closes itself and sometimes Android UI gives the option of stopping the app or waiting for the process.

**Comment by zoroya1** [comment]
It gives 404 error.

**Comment by decipher3114** [comment]
The deleting works fine but the app is not sent to trash

**Comment by IacobIonut01** [comment]
? Just checked and everything works fine in the latest build

> The deleting works fine but the app is not sent to trash

**Comment by decipher3114** [comment]
Oh I just saw. yes the images are sent to the trash but they are sorted as the date of capture, whereas they should be sorted as per the date of deletion.

**Comment by IacobIonut01** [comment]
> Oh I just saw. Yes, the images are sent to the trash but they are sorted as per the date of capture, whereas they should be sorted as per the date of deletion.

That's the default behavior by MediaStore (Media manager from Android). The Gallery is already sorted by the last modification, as far as I see moving it to trash doesn't cause a modification on the file itself, just in the database. Most I can do is sort by the time until the media is automatically deleted (30 days)

**Comment by decipher3114** [comment]
I have checked Google Photos, Files and Gallery Go. All of them sort according to the date of deletion.

Only this app sorts acc. to the date of capture.

**Comment by IacobIonut01** [comment]
> I have checked Google Photos, Files and Gallery Go. All of them sort according to the date of deletion.
> 
> Only this app sorts acc. to the date of capture.

I'll see what I can do

**Comment by IacobIonut01** [comment]
I'll close this issue since it's not related, but you can open a new one for the enhancement
