### ISSUE TITLE
Activity Restart When Image Is Deleted In Image Preview

### ISSUE THREAD

**Issue by gorkijatt** [IacobIonut01/Gallery#137]
I've encountered an issue with your gallery app. When attempting to delete a photo in the image preview, it restarts the activity. Other things are working perfectly fine, such as selecting multiple images for deletion or emptying and restoring the trash.

Tested only on : Pixel 7 (Android 14)

**Comment by gorkijatt** [comment]
https://github.com/IacobIonut01/Gallery/assets/19510688/8802de24-d9cf-4f40-a621-586ebcf97106

**Comment by IacobIonut01** [comment]
The issue is addressed already, use the apk built by Github Actions

**Comment by gorkijatt** [comment]
okae sir ✅
