### ISSUE TITLE
Bottom bar animation is too slow

### ISSUE THREAD

**Issue by niktss** [IacobIonut01/Gallery#140]
On my device at least, the bottom bar pops up slowly, and with what appears to be low FPS:

https://github.com/IacobIonut01/Gallery/assets/57101103/f97a534b-54d7-4c53-9f40-afdc37129cb8

App version: 1.1.0
Device: Samsung Galaxy A52s 5G
Android version: 13

**Comment by IacobIonut01** [comment]
Animation speed is matched with the stock Android delivered on Google Pixels (Android 13 and 14 on Google Pixel 6)


Realistically I can't match for each and every OS from what I know, the animation time is a set value

**Comment by cyberhardt** [comment]
agree
