### ISSUE TITLE
Adding files to an album in background causes current image to shift

### ISSUE THREAD

**Issue by niktss** [IacobIonut01/Gallery#141]
Steps to reproduce:

1. Open an image in Gallery
2. Go to a different app, and add an image to the album you're viewing the image in
3. Return to Gallery

You will now have shifted by 1 image.

You can also reproduce this by taking a screenshot while in the Screenshots album:

https://github.com/IacobIonut01/Gallery/assets/57101103/9fbb01a8-9ff1-478b-955b-e53fef3a79f0

Every time you screenshot, you will get shifted by 1 image.

App version: 1.1.0
Device: Samsung Galaxy A52s 5G
Android version: 13

**Comment by IacobIonut01** [comment]
Thanks, Will be fixed

**Comment by IacobIonut01** [comment]
Please download latest release and let me know, it's fine on my side

**Comment by IacobIonut01** [comment]
After confirmation, close

**Comment by IacobIonut01** [comment]
Closed until confirmation that is still recurring
