### ISSUE TITLE
Gallery defaults to 1 album card per row

### ISSUE THREAD

**Issue by niktss** [IacobIonut01/Gallery#142]
On my device, the default is 1 album per row, which doesn't look right:
![Screenshot_20230825_160022_Gallery](https://github.com/IacobIonut01/Gallery/assets/57101103/b7ef3134-81f0-4e8e-8b1e-84d2283c0e36)
I know that we can adjust album card size, but I'm assuming this is a bug. 

It appears it's on the "edge" of 2 columns; I'm attaching it just in case it's helpful:

https://github.com/IacobIonut01/Gallery/assets/57101103/d3018298-c060-4a51-a7aa-746268d85afc

App version: 1.1.0
Device: Galaxy A52s
Android version: 13

**Comment by IacobIonut01** [comment]
From what I've seen this is consistent on Samsung devices, idk why exactly, but you can change it in the settings

**Comment by niktss** [comment]
Yeah, I know. I was just suggesting changing the DPI threshold to account for that, or do sth like 
```c++
if(device == "samsung"){ workaround }
```

**Comment by IacobIonut01** [comment]
I'll see with 178dp as default with other devices, if it's fine I'll use it
