### ISSUE TITLE
[Feature request] Implement skeleton, or a loading message, when opening the app/an album

### ISSUE THREAD

**Issue by niktss** [IacobIonut01/Gallery#143]
Presently, opening the app or an album shows a message that there's nothing to show, before then loading the view:

https://github.com/IacobIonut01/Gallery/assets/57101103/143c3f66-43a7-4a32-a97f-016f6b0df637

It would be better if instead we showed a [skeleton](https://www.uxdesigninstitute.com/blog/whats-a-skeleton-screen/) or some type of loading message, to make it look more professional.

App version: 1.1.0
Device: Galaxy A52s 5G
Android version: 13

**Comment by st4ycool** [comment]
Google Photos always have something to show! I guess they are pre-loading timeline and albums in advance
But the placeholder or loading message will totally kill the vibe of state-of-art gallery

**Comment by niktss** [comment]
> Google Photos always have something to show!

That's not actually true. Maybe you have a fast device and so it appears instantaneous to you, but if you look at a screen recording slowed down, you can see the skeleton:


https://github.com/IacobIonut01/Gallery/assets/57101103/a0daa88e-86bc-4d35-94ca-c079ecd23035



There is probably performance still left on the table, and we should try to attain that definitely, but a skeleton can help with the perceived speed of the app, especially as you go lower down the device price spectrum. And even a (probably) optimised app like Google Photos uses it for that extra bit of perceived responsiveness, especially on lower-end devices.
