### ISSUE TITLE
"Today" appears right up here & feature request

### ISSUE THREAD

**Issue by Alexandru51** [IacobIonut01/Gallery#144]
![Screenshot_2023-08-26-17-55-46-556-edit_com dot gallery](https://github.com/IacobIonut01/Gallery/assets/94460645/bf41baf0-bd29-4208-a632-99046b34515a)

And add this sliding selection thing, like how Aves Gallery has:

https://github.com/IacobIonut01/Gallery/assets/94460645/f814932c-5d00-4a01-b5cb-1c2cd4022959

**Comment by IacobIonut01** [comment]
Try the latest apk from Github Actions (select the latest build, go to artifacts)

**Comment by IacobIonut01** [comment]
And regarding the feature request, I've already considered adding it, and I'm currently working on it

**Comment by Alexandru51** [comment]
Ok

**Comment by Alexandru51** [comment]
I tried, still shows

**Comment by Alexandru51** [comment]
@IacobIonut01 by the way, i updated the romanian translation

**Comment by IacobIonut01** [comment]
> I tried, still shows

What device?
Which OS (if custom, specify)
Also what's the smallest width reported in Settings > System > Developer Options

**Comment by Alexandru51** [comment]
Xiaomi Redmi Note 9 (merlin)
Android 12
384dp

**Comment by IacobIonut01** [comment]
Are you running MIUI? Must be an issue with how MIUI reports statusbar size in the OS. I'll have to look for a workaround

**Comment by Jean-BaptisteC** [comment]
Reproduced on Pixel 6 - Android 13

**Comment by IacobIonut01** [comment]
> Reproduced on Pixel 6 - Android 13

Make sure you're using the latest apk from Github Actions.

My test device is the Pixel 6 so this is impossible on the latest build

**Comment by Alexandru51** [comment]
> Are you running MIUI? Must be an issue with how MIUI reports statusbar size in the OS. I'll have to look for a workaround

Yes, i do

**Comment by Jean-BaptisteC** [comment]
I have tested with this apk https://github.com/IacobIonut01/Gallery/actions/runs/6000344875 and I'm able to reproduce the problem.

**Comment by Alexandru51** [comment]
> I have tested with this apk https://github.com/IacobIonut01/Gallery/actions/runs/6000344875 and I'm able to reproduce the problem.

Still same thing
![Screenshot_2023-08-28-22-54-59-157-edit_com dot gallery](https://github.com/IacobIonut01/Gallery/assets/94460645/fbf94c51-05b2-41cb-8381-ce82f3f9a307)

**Comment by IacobIonut01** [comment]
Wait for the last commit to build and see, should be fine

**Comment by Alexandru51** [comment]
Now it's fixed 👍🏻
