### ISSUE TITLE
[BUG] can't delete media stored on the MicroSD card

### ISSUE THREAD

**Issue by 5wHN28Dg** [IacobIonut01/Gallery#159]
**Describe the bug**
The app can't delete media stored on external storage devices, in my case a MicroSD card. 

**To Reproduce**
Just try to delete any image or video on the MicroSD card and nothing will happen, clicking `delete` does absolutely nothing

**Expected behavior**
The file should be deleted or moved to the trash pin

**Smartphone**: -
- Device: Galaxy Note 9
 - OS: Android 13
 - Version: 2.0.0

**Comment by IacobIonut01** [comment]
Confirmed

**Comment by IacobIonut01** [comment]
**Info**
As expected, Removable Storage (SDCards) don't support moving media to 'trash'.

**New behavior**
A new UI will be available soon informing the user that the media he proceeds to delete will be a permanent action (with a prompt asking if he wants to continue or not, and to never show the prompt again)

**Comment by IacobIonut01** [comment]
![Deletion warning](https://github.com/IacobIonut01/Gallery/assets/19311643/181f57e4-622d-4594-9372-40133489bcf9)

**Comment by 5wHN28Dg** [comment]
> with a prompt asking if he wants to continue or not, **and to never show the prompt again**

Maybe also add an option to not show this prompt again **only for this session** so when the user opens the app again and tries to delete a file he will get the prompt again, this will work as a reminder to the user and help avoid accidents just in case he forgets that this is an irreversible action

**Comment by IacobIonut01** [comment]
Fixed here: https://github.com/IacobIonut01/Gallery/commit/095bfa4c80226ae9b16b022fdc9265cca60b17bb
