### ISSUE TITLE
[BUG] Back gesture in photo info page

### ISSUE THREAD

**Issue by jerichoi224** [IacobIonut01/Gallery#166]
**Describe the bug**
Not sure if it's a bug, but when in the picture info, I can't use the back gesture... 

**To Reproduce**
1. Go to image
2. Slide up to show info
3. Try the back gesture 

**Expected behavior**
I think it would be intuitive to have the info disappear with the back gesture 

**Screenshots**

https://github.com/IacobIonut01/Gallery/assets/4184001/93d7fec0-7b88-450c-9f6c-5ba2b99d5683

**Smartphone (please complete the following information):**
 - Device: nothing phone 1
 - OS: android 13

**Comment by IacobIonut01** [comment]
Confirmed.

It's a compose bug and I'm still struggling to understand why and how to fix this.

Thanks
