### ISSUE TITLE
[BUG] deleted images aren't deleted

### ISSUE THREAD

**Issue by fallsdevil** [IacobIonut01/Gallery#173]
## I'm trying to delete some images and nothing happens.

selecting one or more images at a time, I click delete and the images remain the same. but, seconds before I had managed to delete other images and it worked correctly.

Some solutions I tried were:
- delete the cache;
- force stop;
- close and open the app after a few minutes.

**Smartphone Motorola:**
 - Device: Moto E22
 - OS: Android 12 (Go Editon)
 - Version: 2.0.0

**Comment by IacobIonut01** [comment]
I'm sorry but I can't seem to reproduce the bug on any of my devices or emulators

**Comment by fallsdevil** [comment]
strange... could it be a bug on my smartphone? In fact, I just redid this action and it worked. 
Anyway, thank you for your response!

**Comment by fallsdevil** [comment]
> I'm sorry but I can't seem to reproduce the bug on any of my devices or emulators

I think I figured out what's going on! Apparently, images stored on micro SD card cannot be deleted, but images on internal storage are deleted easily.
Also, I gave everyone storage permission and I don't know this is happening...

**Comment by IacobIonut01** [comment]
> > I'm sorry but I can't seem to reproduce the bug on any of my devices or emulators
> 
> I think I figured out what's going on! Apparently, images stored on micro SD card cannot be deleted, but images on internal storage are deleted easily.
> Also, I gave everyone storage permission and I don't know this is happening...

Then you should download the latest build from Github Actions - deleting media from sdcard is already fixed

**Comment by IacobIonut01** [comment]
Please confirm and close the issue.

**Comment by fallsdevil** [comment]
I'm using the latest version, but it still has this bug...

This [link](https://imgur.com/a/wyDARAx) contains a video of the process and a print of the current version of the Gallery.

**Comment by IacobIonut01** [comment]
This is the latest version https://github.com/IacobIonut01/Gallery/actions/runs/6328646997

Download the Artifact (it will download as zip), extract and install the apk
![image](https://github.com/IacobIonut01/Gallery/assets/19311643/0b73f747-e012-42ab-8410-76804573fd3f)
