### ISSUE TITLE
[Feature Request] Old navigation bar

### ISSUE THREAD

**Issue by NeuroException** [IacobIonut01/Gallery#174]
Please consider giving the user an option to disable the floating navigation bar. It looks good though, but is very unpractical for me. A toggle in the settings would be enough. This app is really great, and the best modern opensource gallery app i could find. I would love to recieve further updates, but for now, i have to stick with the latest version before the floating navigation bar. Thanks for your time.

**Comment by IacobIonut01** [comment]
I will add an option to go back to the old navigation style.

Thanks for your feature request!
