### ISSUE TITLE
[Enhancement] Scroll Bar

### ISSUE THREAD

**Issue by harryjph** [IacobIonut01/Gallery#189]
**Is your feature request related to a problem? Please describe.**
First of all, your app is awesome! Thank you so much.

I have a large media library and it seems like there's no way to scroll through it quickly, for example to a particular month.

**Describe the solution you'd like**
A scrollbar would be amazing!

**Comment by IacobIonut01** [comment]
Thanks, 

Yeah I know about the scrolling bar necessity, I'm still looking for a solution on it
