### ISSUE TITLE
Permissions enhancement: adding "media only" permission

### ISSUE THREAD

**Issue by serrq** [IacobIonut01/Gallery#2]
Currently I am obliged to grant permission to manage all the files of my device.

This is not necessary: Aves requires permissions only for the media file directory (images, videos).

I therefore ask for this enhancement to be introduced.

**Comment by IacobIonut01** [comment]
That permission is currently required to access trashed media (marked as invisible with the name .trashed-*). I'm currently trying to find a workaround to avoid using that permission, since other Google apps like Gallery Go and Photos don't require that.

Thanks!

**Comment by IacobIonut01** [comment]
Thanks for the suggestion!
