### ISSUE TITLE
versionCode

### ISSUE THREAD

**Issue by IzzySoft** [IacobIonut01/Gallery#20]
Please remember to [increase `versionCode`](https://github.com/IacobIonut01/Gallery/blob/v1/app/build.gradle.kts#L16) with each release (and while on it, also to adjust `versionName`). Your current release (v1.0.1 according to its tag name) identifies as `1.0+1`, the very same as the previous v1.0. This is a problem for multiple reasons:

* Android uses `versionCode` to tell versions apart. A higher number means an update, so the user is notified accordingly. An unchanged number means it's the same version as installed, so the user is not notified. A lower number means an older version as installed, so the user is prevented from "simply installing it over the existing one" (e.g. database structures might have changed, and would mean a broken install otherwise)
* If `versionName` is always the same, there's no easy way for a user to even know which version is installed on a device :wink:

Thanks for taking care!

**Comment by IacobIonut01** [comment]
Thanks for pointing it out! I'll make sure next releases complain with the standard

**Comment by IzzySoft** [comment]
Thanks! This helps a lot for the update process. Btw, your app is [available here](https://apt.izzysoft.de/fdroid/index/apk/com.dot.gallery) and thus can be easily found, installed and kept up-to-date using any [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) (which is what increasing `versionCode` is important for). If you wish, you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme for the convenience of your users :smiley:

**Comment by IacobIonut01** [comment]
Done. Next release will contain a proper versionName incremention

**Comment by IzzySoft** [comment]
Cool, thanks! So whenever you feel ready, be welcome to merge the PR I just opened to add this badge to the row in the Readme:

[![IzzyOnDroid](https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/com.dot.gallery)](https://apt.izzysoft.de/packages/com.dot.gallery/)

It will update to show the version currently available in my repo – so with the next release, that should match (i.e. you might wish to wait with the merge until your next release is out).
