### ISSUE TITLE
[BUG] Impossibility to install Gallery APK

### ISSUE THREAD

**Issue by fallsdevil** [IacobIonut01/Gallery#201]
**Describe the bug**
I’m trying to install Gallery on a smartphone, but all APK files are giving a crash when installing

**To Reproduce**
Downloading from browser on this website:
1. go to the latest version
2. and click download
3. after finishing, click on "open"
4. the installation starts, but in a matter of seconds shows an error message when installing

**Expected behavior**
I would like to be able to use this app on this specific smartphone

**Screenshots**
![IMG-20231023-WA0003](https://github.com/IacobIonut01/Gallery/assets/142761950/e794e0c1-b601-4b37-91d7-a66b5084cee8)
![IMG-20231023-WA0002](https://github.com/IacobIonut01/Gallery/assets/142761950/2204176a-5f2d-4932-894e-648517738df8)

**Smartphone:**
 - Device: Samsung Galaxy A01 Core
 - OS: Android 10 (Go Editon)
 - Version 2.0.0 Beta # 3

**Additional context**
As some alternative attempts I tried to install old versions that gave the same error, I also tried to do the installation by the file manager (Google Files, first screenshot) instead of doing directly in the browser after downloaded, but I didn’t get a positive result. As a last attempt, I tried to install using *Obtanium*, which is the second screenshot.

**Comment by IacobIonut01** [comment]
Min: Android 11
