### ISSUE TITLE
[Enhancement] Please use local pricing!

### ISSUE THREAD

**Issue by kyoyacchi** [IacobIonut01/Gallery#204]
Hi. I'm a human who lives in Türkiye (or Turkey),
Congratulations on adding your app to Play Store.
But please use local pricing for your app, it's too expensive for a gallery app
![Screenshot_20231027-003311](https://github.com/IacobIonut01/Gallery/assets/63583961/ec3ba30a-d1de-463c-b65c-5907b24354ec)
As you can see in the screenshot it says "TRY 58.99"

1 $ = 28₺
![Screenshot_20231027-003716](https://github.com/IacobIonut01/Gallery/assets/63583961/bf7f8260-9cb7-4f76-98fc-cd7fb34bf665)

2 $ = 56.34₺

**Comment by IacobIonut01** [comment]
I'm still new to google play pricing, I'll fix that as soon as possible!

**Comment by IacobIonut01** [comment]
I've updated the prices, let me know if the price is right for local currency
