### ISSUE TITLE
[Enhancement] SD Card icon

### ISSUE THREAD

**Issue by fallsdevil** [IacobIonut01/Gallery#205]
**Is your feature request related to a problem? Please describe.**
No, only related to the ease of identifying which storage the files are in.

**Describe the solution you'd like**
Adding a simple icon in the corner of the album image, or something similar to that.

**Describe alternatives you've considered**
More would be easier to identify the albums that are on the SD Card, using some visual feature, for example as an sd card icon similar to other galleries, or a subtext below the album name written "SD card" or something in that sense.

**Additional context**
This is a screenshot as an example, using the Samsung gallery.
![Screenshot_20231026_201532](https://github.com/IacobIonut01/Gallery/assets/142761950/e41177ca-a0aa-4fd5-bd85-39cf2be89e9c)

**Comment by IacobIonut01** [comment]
Good catch, thanks!
