### ISSUE TITLE
[Enhancement] Please, please, get rid of the Network Permission!

### ISSUE THREAD

**Issue by gordongw** [IacobIonut01/Gallery#206]
I was happy to donate twice, as soon as I found this gem of an app. Imagine my dissapointment when upon installing version 2.0 from scratch I saw the mandatory Network Access Permission. From a privacy point of view I find this completely unacceptable. Please, make this permission optional and I will be happy to keep donating to the project. 

Thanks!

**Comment by IacobIonut01** [comment]
Hi! The no-maps version doesn't use the internet at all, I'll stirp down that permission from the no-maps variant, but the Internet is not a permission you can ask to be granted or not in stock Android, some skins can let you do exactly that, restrict the internet access to the app. Let me know if downloading the no-maps permission with the internet permission removed is good enough

**Comment by gordongw** [comment]
> Let me know if downloading the no-maps permission with the internet permission removed is good enough.

Hi and thank you for responding so promptly! Yes, this would be a completely satisfactory solution.

**Comment by IacobIonut01** [comment]
You can download the internet-free no-maps Gallery apk from https://github.com/IacobIonut01/Gallery/actions/runs/6662838535, under 'Artifacts'
