### ISSUE TITLE
[Enhancement] Allow moving to SD Card

### ISSUE THREAD

**Issue by GitGitro** [IacobIonut01/Gallery#208]
**Is your feature request related to a problem? Please describe.**
Not really a problem, at least it seems intentional not allowing moving to the SD card

**Describe the solution you'd like**
I believe with the **MANAGE_EXTERNAL_MEDIA** permission you can implement moving files from one album inside the internal storage to an external storage. I know it's not best practice to use that permission anymore and would be hard to publish to the play store, maybe making it optional would be ideal.

**Additional context**
Lovely app, thank you in advance if you decide to add this.

**Comment by IacobIonut01** [comment]
Yes, I'm aware that if I use that permission it would allow moving albums more freely,

I'll see if I can add the feature and comply with everything
