### ISSUE TITLE
[Enhancement] making delete confirm dialog optional

### ISSUE THREAD

**Issue by jerichoi224** [IacobIonut01/Gallery#209]
I previously asked for confirm delete dialog, which I think is necessary.
However, on the recent version from the playstore, when deleting, after I go through the confirm dialog, I get another popup asking to confirm like below.

![Screenshot_20231029-141209](https://github.com/IacobIonut01/Gallery/assets/4184001/31cae008-94c7-4f52-a3e6-d031f9433cb3)

I believe this is something implemented by the phone OS. This is mentioned in a flutter package [here](https://pub.dev/packages/photo_manager#remove-all-non-exist-entities)

"Some operating systems will prompt confirmation dialogs for each entities' deletion, we have no way to avoid them. Make sure you're using the correct method, and your customers accept repeatedly confirmations."

I have previously requested for the dialog before because in version 1.x.x, this dialog didn't show up for me. Now that I'm using the recent version, however, I get this dialog so I got to confirm it twice, which is kind of annoying. 
I think it could be something changed in this app, or it could be something from phone OS update, but either way.

I think it would be nice if there was a way to disable to confirm dialog by the gallery, since the OS already asks for it. 

Also, fyi, from my understanding Google play store doesn't allow adding url for payment to app other than in-app payments, so you might want to remove the donate button from the playstore version so the app doesn't get in trouble.

**Comment by IacobIonut01** [comment]
![Screenshot_20231029-100716.png](https://github.com/IacobIonut01/Gallery/assets/19311643/6ff974d8-35ae-44c6-9e9d-16d9b5a6ce5e)

Make the app media manager

**Comment by jerichoi224** [comment]
Ahh I see. didn't realize it was issue with that.. oops. thx it works fine :)

**Comment by kyoyacchi** [comment]
> ![Screenshot_20231029-100716.png](https://user-images.githubusercontent.com/19311643/278858656-6ff974d8-35ae-44c6-9e9d-16d9b5a6ce5e.png)
> 
> Make the app media manager

How did u open that? My phone doesn't have it. Making it default does the same thing?

**Comment by IacobIonut01** [comment]
> > ![Screenshot_20231029-100716.png](https://user-images.githubusercontent.com/19311643/278858656-6ff974d8-35ae-44c6-9e9d-16d9b5a6ce5e.png)
> > 
> > Make the app media manager
> 
> How did u open that? My phone doesn't have it. Making it default does the same thing?

Should be under Settings > Apps > Special app access 

But you can clean the data of the Gallery and it should show a pop up at the top regarding that and it should launch that menu directly
