### ISSUE TITLE
Enhancement: Mirror MediaStore Database internally 

### ISSUE THREAD

**Issue by IacobIonut01** [IacobIonut01/Gallery#21]
Create a background worker to mirror MediaStore Database to an internal Room database for faster loading speeds

**Comment by Chandra-Mauli-Sharma** [comment]
Hi @IacobIonut01, I would like to work on this. Can you assign this to me?

**Comment by IacobIonut01** [comment]
Sure thing!

**Comment by Chandra-Mauli-Sharma** [comment]
Thanks

**Comment by Chandra-Mauli-Sharma** [comment]
What does "Mirror" actually mean? Are we required to saved the saved media store values in room db for persistence and smoothly?

**Comment by IacobIonut01** [comment]
All the data that the "Media" and "Album" data class uses will be retrieved from MediaStore, Stored in Room then the Room database will display all the media.


A contentFlowObserver (defined in the app) will be used to observe MediaStore changes and update the Room accordingly.

**Comment by Chandra-Mauli-Sharma** [comment]
Ok thanks

**Comment by IacobIonut01** [comment]
I decided that it's not faster that getting MediaStore database at runtime, check branch v1-wip for an example of the implementation

**Comment by Chandra-Mauli-Sharma** [comment]
Looks great
