### ISSUE TITLE
[Enhancement] Crowdin link in app and github project description

### ISSUE THREAD

**Issue by Cwpute** [IacobIonut01/Gallery#213]
**Is your feature request related to a problem? Please describe.**
I'd like to translate tge app in french, but i didn't know the app had a Crowdin page. I had to search through the issue to find the correct link.

**Describe the solution you'd like**
The Crowdin page should be better communicated about! Most projects put a link on the github project page, as well as directly in the app with a little text requesting help for translation.

**Comment by IacobIonut01** [comment]
Hi, I guess it could be confusing for some, but the crowdin link is already available in the readme under the [localized: 34%] chip.

Thanks for letting me know, I'll update the README page and to explicitly link the crowdin page as well

**Comment by Cwpute** [comment]
Oh i realize i'm using Gallery 1.1.0 from Fdroid which hasn't been updated to 2.0.0 already, this chip must not be present in that old version i guess.

**Comment by Cwpute** [comment]
Right now, regarding this issue ? or generaly speaking when it does update on Fdroid ?

**Comment by IacobIonut01** [comment]
Generally speaking

**Comment by Cwpute** [comment]
The update slipped under my radar unfortunately… i didn't take the time to note any differences, but i guess everything works well enough since i haven't seen glareng issues.

Regarding a ling to the Crowdin project: none appears to be visible in the Parameters page. Should there be one ?

On another note: Fdroid version is stil 2.0.0, and hasn't been updated to 2.0.1 yet. Was about to report about the screen going to sleep during videos #236 but it seems this was supposedly fixed… in a version unavailable on Fdroid.

**Comment by IacobIonut01** [comment]
I'm sorry for the inconvenience, I'll make sure the next update will be available right away after the release, which is happening soon!

**Comment by franco27** [comment]
The Crowdin logo is on the homepage, but when I click on it, it redirects me to the image and not to the Crowdin website for translation.

**Comment by IacobIonut01** [comment]
> The Crowdin logo is on the homepage, but when I click on it, it redirects me to the image and not to the Crowdin website for translation.

I made a mistake xD

I'll edit tomorrow since it's late here, but you can open the page by clicking on the [localized: 59%] button

**Comment by franco27** [comment]
Ok, thank you
