### ISSUE TITLE
[Enhancement] Add 'Uncategorized' album

### ISSUE THREAD

**Issue by NeuroException** [IacobIonut01/Gallery#214]
**Is your feature request related to a problem? Please describe.**
No related to a problem.

**Describe the solution you'd like**
Add a "uncategorized"-album. This pseudo album would show every image that has not been added to an album. I like my gallery sorted and categorized, and this would help me see if any image is left to categorize.

**Comment by IacobIonut01** [comment]
Hi, all the albums and so are grouped by the MediaStore, there's no 'wild' or uncategorized media, just media that is inside a specific album.
Even media under root storage is categorised as an album
