### ISSUE TITLE
App doens't open after restart (error) after switching on monthly view

### ISSUE THREAD

**Issue by pflanzenandi** [IacobIonut01/Gallery#219]
2.0.0, Fresh install, all permissions, Android 14

**Comment by IacobIonut01** [comment]
> 2.0.0, Fresh install, all permissions, Android 14

Are you using stock android ?
I've never encountered this issue nor I can't reproduce

**Comment by pflanzenandi** [comment]
Then it must have something to do with GrapheneOS.

**Comment by DKMellow** [comment]
Also on Garapene OS, Android 13, and the apps crashes at launch after the update.

[crash-com-dot-gallery-02-11_20-10-01.zip](https://github.com/IacobIonut01/Gallery/files/13243643/crash-com-dot-gallery-02-11_20-10-01.zip)

**Comment by IacobIonut01** [comment]
Please check update 20079, should have fixed all issues about this

**Comment by DKMellow** [comment]
Can confirm the issue is fixed. Thank you!
