### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [IacobIonut01/Gallery#220]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, DASH, XLM, FTM, XMR addresses available for donations (addresses have to be copyable).

Following an example from other developers.

![1000092943](https://github.com/cypherstack/stack_wallet/assets/113377431/44b05c36-ec6d-42db-b055-69272ccd4c63)

**Comment by IacobIonut01** [comment]
Hi, I'll add them a bit later but these are the addresses for

ETH, AVAX, POLYGON:

```
0x707eF0E95e814E05efadFD3d3783401cfbE8D11E
```

Thanks

**Comment by IacobIonut01** [comment]
Now yes

**Comment by IacobIonut01** [comment]
> Please add also Epic Cash to the cryptocurrencies' list. In order to show the Epic Pay wallet, you have to add manually the Stack repo in F-droid:
> 
> https://fdroid.stackwallet.com/
> 
> 76 4B 42 62 F7 57 50 A5 F6 20 A2 05 CE E2 88 6F 18 63 5F BD A1 8D F4 07 58 F5 A1 A4 5A 95 0F 84
> 
> More info: https://epic.tech/
> 
> ![1000095803](https://github.com/IacobIonut01/Gallery/assets/113377431/8a08472e-0fc4-411e-8a42-06f3a81a1312)
> 

esWaroB8AQXZuaEJWtraPomNH3Lg1JRP3EVxr6batoFuqvf3hrHP@epicbox.epic.tech

**Comment by IacobIonut01** [comment]
> Next months I make a new crypto order and I try to send you EPIC 💪
> 
> Don't forget to add the EPIC address in next app releases (in-app I mean).

Thanks, the donation UI should be available by the next release

**Comment by IacobIonut01** [comment]
> Have you already a preview of the donation UI? I am curious about it 😁
> 
> 

I'll share soon, I haven't done it yet

**Comment by sonalder-darlene** [comment]
Will you add the possibility to accept BTC and XMR ? That's two popular option in the open source and privacy sphere.

**Comment by IacobIonut01** [comment]
Will be available in the next update

**Comment by IacobIonut01** [comment]
> I mean, you will send it in f-droid?

Yes

**Comment by IacobIonut01** [comment]
Added UI for most of the requested Addresses!

**Comment by IacobIonut01** [comment]
https://github.com/IacobIonut01/Gallery/commit/aef83bd6eb5bcae987879f090b6a85f2a6630036
