### ISSUE TITLE
[2.0.0 nomap] Troubles with scrolling in the timeline

### ISSUE THREAD

**Issue by serrq** [IacobIonut01/Gallery#221]
OnePlus CPH2399
Android 13
Gallery 2.0.0 (20070) nomap edition

• When I scroll the images in the timeline they seems to crush and impact each other in a disorderly manner.
For privacy reasons I cannot provide the screenshot.

• Might you adding the nomaps edition in Izzy or fdroid repo too?

**Comment by IacobIonut01** [comment]
Thanks for reporting, it's a slight visual bug that happens only in the album timeline, I'm already aware of it but it's not really a priority right now. The permissions should be reduced from 20079
