### ISSUE TITLE
Ability to hide photos/videos in a hidden folder within the app

### ISSUE THREAD

**Issue by Zaxx69** [IacobIonut01/Gallery#232]
We should be able to create a hidden folder to hide our photos and it should be protected by our phone password or a custom password .this folder can't be accessed by our phone

A little suggestion about implementing it - a hold press on either on timeline or album tab to open the folder with password

Also the ability to hide many photos / videos at once

**Comment by IacobIonut01** [comment]
Duplicate of #5, explained the plans inside.
Thanks
