### ISSUE TITLE
Some chronology view enhancements

### ISSUE THREAD

**Issue by Cwpute** [IacobIonut01/Gallery#238]
Two things regarding chronology view:
1. The date displayed in the top left corner while scrolling is always the same date and does not change depending on the day's pictures displayed at the topmost of the screen.
2. When scrolling like that, making the menu items completely disapear is disturbing, as it suddenly changes how the app looks. It should either use animations or transparency to make these itmes disapear, so that they still leave space for the photos below, are still usefu, but without being disturbing.

Both of these can be seen in the following video: (sorry for the watermark - if you know of a free, lightweight video-editor for android let me know…)

https://github.com/IacobIonut01/Gallery/assets/80604512/dbd18c13-bc79-4b99-ac5f-d709775f59fb

**Comment by IacobIonut01** [comment]
1. Please update to the latest release
2. There's an animation, you must have it disabled system-wide or reduced the animation factor to 0x in developer settings.

**Comment by Cwpute** [comment]
… 😳
I didn't know i had them disabled. Thanks for the heads up. It looks much better.

But i don't understand… other apps i've used still had some animations, your is the first one i see which has its own animations bound to a system-wide setting…

**Comment by IacobIonut01** [comment]
> … 😳 I didn't know i had them disabled. Thanks for the heads up. It looks much better.
> 
> But i don't understand… other apps i've used still had some animations, your is the first one i see which has its own animations bound to a system-wide setting…
> 
> Will i have to _endure_ one second of animation on _everything_ i do on my phone to have this issue on your app solved for me ?

I set mine to 0.5x, I find it a very balanced

**Comment by Cwpute** [comment]
> I set mine to 0.5x, I find it a very balanced.

That's what i did in the end as well. thanks
