### ISSUE TITLE
[Feature Request] Show location

### ISSUE THREAD

**Issue by pabloscloud** [IacobIonut01/Gallery#25]
Could show the location in the info view and let the user open it in their map app

**Comment by IacobIonut01** [comment]
By 1.1 Release the Media Info Dialog will be revamped. In the revamp the location map will be available as well including some new features like photo editing.

**Comment by IacobIonut01** [comment]
Done.
[MediaInfo: Improve BottomSheet UI](https://github.com/IacobIonut01/Gallery/commit/07efb9ce84c0cabd6461d302c0d5cf368860017c)
