### ISSUE TITLE
[BUG] Moving files does not update the grid

### ISSUE THREAD

**Issue by jerichoi224** [IacobIonut01/Gallery#257]
**Describe the bug**
When inside the album image grid page, the grid does not update immediately when moving files. 
Deleting files will automatically remove them from the grid and shift the rest, and I think it should do the same for moving files since they are no longer in the folder.

**To Reproduce**
1. Go to Albums
2. Choose any alblum
3. Select an image
4. move to another folder

**Expected behavior**
Image gets moved to the new folder - works properly
Image gets removed from the album grid - doesn't happen.

**Smartphone (please complete the following information):**
Nothing Phone 1

**Comment by IacobIonut01** [comment]
Known bug, I'm still working on fixing it
