### ISSUE TITLE
[Enhancement] Gestures for certain actions in Timeline View.

### ISSUE THREAD

**Issue by aqilc** [IacobIonut01/Gallery#258]
### Is your feature request related to a problem? Please describe.
A lot of Gallery apps I've use have features enabling you to Zoom out to view more photos, subtly changing views and layout in between. For example, the Samsung Gallery App's Timeline view changes by every zoom level from Day to Month to Year. This would be really cool to have in this app, as it lets you scroll through many more photos and appreciate more memories at once! I'm also used to swiping down to close out of looking at a photo, since it's easier than reaching for the back button. This was also a feature I missed in many other stock android Gallery apps.

Thank you so much for making this app by the way, other than these basic features your app is much better than any stock alternatives I've used! Please keep going and I hope this app turns into something you're proud of.

### Describe the solution you'd like
Zoom in and Zoom out gesture mapping to getting more photos on screen at once with a bigger or smaller Timeline frame. Swipe down mapping to go back to the Timeline view.

**Comment by IacobIonut01** [comment]
Forgot to close this but it's finished in https://github.com/IacobIonut01/Gallery/commit/93ce59e7fca739b84e16dcf760516e3f68ea96e1
