### ISSUE TITLE
[Enhancement] Create different string for the heart-action 'favorite' in media view

### ISSUE THREAD

**Issue by ColorfulShire** [IacobIonut01/Gallery#273]
**Is your feature request related to a problem? Please describe.**
Currently there is only one string for 'favorites', which means the word on the button for showing the favorites is the same as the button for adding a single picture/video to the favorites. This is a problem in some languages.

**Describe the solution you'd like**
I suggest creating a new string for the 'heart' action on the screen when you view a picture/video (the screen where you can also share, edit, delete and trash)

**Comment by IacobIonut01** [comment]
Do you have any suggestions for the heart string?
