### ISSUE TITLE
[Enhancement] Allow to hide photos from certain albums/folders in the timeline/photos view

### ISSUE THREAD

**Issue by eennoo** [IacobIonut01/Gallery#274]
**Is your feature request related to a problem? Please describe.**
As a user I have added photos from my DCIM folder and my Screenshot folder. Atm the screenshots show up in the timeline view. I do understand that there is a Blacklist feature, but this hides the Screenshot folder from the album view as well.

**Describe the solution you'd like**
I'd like to have an option to choose which albums/folders/sources to show in the timeline. This so that for example, the screenshots don't pollute my timeline view where I only want to see my photos. 

So a similar solution that you've implemented for the Blacklist feature, but where you only blacklist certain albums from the timeline view. Because I still want to have access to the Screenshot folder in the albums view.

**Describe alternatives you've considered**
N/A

**Additional context**
Timeline view = The start view of the app (couldn't find a name for it in the app)

**Comment by IacobIonut01** [comment]
So, basically an option to either hide from both timeline and albums or just from timeline?

**Comment by eennoo** [comment]
It depends on the users of course. But today the Blacklist is for both. So maybe have an option:

"Albums to show"

Maybe just show the different albums in thav view and have some checkbox-like UI component for Timeline and Albums. So the user could quickly uncheck the albums that they don't want to be shown for either view. Just a very quick suggestion. 
Albums to the left in a column and then the column to the right having the ui components that allow you to show hide for eitehr view.

**Comment by IacobIonut01** [comment]
Today will be available as nightly

![Screenshot_20240813-142059](https://github.com/user-attachments/assets/3fd9c928-e1b3-4b9f-b7aa-274ac5a4c227)
![Screenshot_20240813-142128](https://github.com/user-attachments/assets/d3c355e4-c26d-4a48-a49d-b1c983f3a274)
![Screenshot_20240813-142028](https://github.com/user-attachments/assets/8096178a-03d2-4c98-b00a-b6f2ba5bda2d)
![Screenshot_20240813-142043](https://github.com/user-attachments/assets/d29be70d-a7b1-45e4-bd53-26c6c4d09082)
![Screenshot_20240813-142331](https://github.com/user-attachments/assets/d0a77451-22e1-4721-a968-c75fc28bc2d4)
![Screenshot_20240813-142323](https://github.com/user-attachments/assets/7a827071-c416-49d3-9fab-af95446bc6f4)
![Screenshot_20240813-142120](https://github.com/user-attachments/assets/917d7717-3e0e-4a23-b6a0-8229464793c0)
![Screenshot_20240813-142039](https://github.com/user-attachments/assets/4574f035-6741-4829-9ce0-57c192966432)
![Screenshot_20240813-142048](https://github.com/user-attachments/assets/dd8b06ab-7ace-423c-9192-4657bf83b9bc)
