### ISSUE TITLE
Reproducible build failed

### ISSUE THREAD

**Issue by linsui** [IacobIonut01/Gallery#277]
[diff.zip](https://github.com/IacobIonut01/Gallery/files/13539745/diff.zip)

We have saw similiar issues on other apps. See https://gitlab.com/fdroid/fdroiddata/-/issues/3138.

**Comment by linsui** [comment]
It doesn't help.

**Comment by linsui** [comment]
Please update Compose Compiler to 1.5.6 which should fix the problem. See https://gitlab.com/fdroid/fdroiddata/-/issues/3138

**Comment by IacobIonut01** [comment]
Updated
