### ISSUE TITLE
[BUG] Possible Trojan detected

### ISSUE THREAD

**Issue by Gersado** [IacobIonut01/Gallery#278]
**Describe the bug**
A possible Trojan has been detected in the gallery app. It seems to affect both the GitHub and F-droid versions. 

**To Reproduce**
1. Download any of the apks from F-droid or GitHub.
2. Go to Virus Total (https://www.virustotal.com/gui/home/upload) and click "Choose file".
3. Select the downloaded apk and click confirm. 
4. Wait for the results.

**Expected behavior**
One of the results from the scan claims to have found a Trojan in the app.

**Screenshots**
Results are from the Github version, the F-droid version returns the same results.
![gallery-github](https://github.com/IacobIonut01/Gallery/assets/152810782/16f32a31-f5a9-49b6-a0d7-61647f7972dd)

**Additional context**
I've detected similar results from another gallery app, Aves. Much like with Aves, I wanted to bring this up to the devs to make sure that the app isn't compromised.

**Comment by IacobIonut01** [comment]
Most likely it's a false positive.

Since only 1 out 63 detected anything suspicious and the apks aren't compromised, the GitHub apks used for release are compiled by Github Actions and the source code of the apk is already available right here for manual checking if needed
