### ISSUE TITLE
Start app in album view

### ISSUE THREAD

**Issue by dasmaetthes** [IacobIonut01/Gallery#281]
Please offer the possibility to start the app in the album view instead of the timeline.

**Comment by eylenburg** [comment]
Agreed! Or let the app start in whatever view was last used.

**Comment by KaiserCalm** [comment]
@IacobIonut01 I saw your comit makes the app use the last page that was open, but would it still be possible to put all three of these options into a toggle in the settings?

Something like:
```
Default View When Opened:
1. Timeline
2. Albums
3. Last Viewed
```
