### ISSUE TITLE
Adapt picture size in the timeline view via settings

### ISSUE THREAD

**Issue by goebbe** [IacobIonut01/Gallery#282]
**Problem:**
When scrolling through the pictures in the timeline view, searching for a certain pic, the picture previews (thumbnails) are too small for me.
Background: I use a medium size smartphone, and 4 pics in a row leads to small previews.  

**Solution:**
It would be great if it would be possible to adapt the size of the previews (thumbnails) in the time-line view via the settings. 
For me, 3 pictures in a row would be perfect on my smartphone. But I imagine that, e.g. on a tablet also, 5-6 pictures per row would be just fine. 

Edit: Now, I installed Gallery on my tablet - and was surprised by the very small picture (preview) size and many pictures per row. So it seems that currently the picture size is fixed - and not, as I wrongly assumed, the number of pictures per row.  

**Alternative solution:**
Adaptable size of the timeline previews via gestures (2 fingers zoom).

**Additional context**
I don't have the best eyesight.  :-) 

Thank you very much for providing the Gallery app!

**Comment by camoz** [comment]
IMO the 2 finger zoom solution is preferable over an explicit setting: It's (nowadays) more intuitive, faster to adjust, same in functionality, and would not introduce an additional setting's option.

**Comment by OpenSaned** [comment]
> IMO the 2 finger zoom solution is preferable over an explicit setting: It's (nowadays) more intuitive, faster to adjust, same in functionality, and would not introduce an additional setting's option.

This is standard in most Gallery apps Nowadays, so its probably a good idea to implement.

**Comment by goebbe** [comment]
@cmoz @OpenSaned I agree. However, I think it is up to the developers to decide if and how different picture sizes should be supported.  2 finger zoom is likely to be more involved than an additional option with other (fixed) picture sizes in the settings.

**Comment by IacobIonut01** [comment]
I am closing this as this feature is now available via the 2 Finger zoom gesture
