### ISSUE TITLE
[BUG] Cannot open files from Little File Explorer

### ISSUE THREAD

**Issue by Cwpute** [IacobIonut01/Gallery#290]
**Describe the bug**
I can't open any files in Gallery if i try to access them from the [Little File Explorer app](https://martinmimigames.github.io/projects/little-file-explorer). Gallery opens up, but the image is either fully black, or blank.
Using another gallery app ([Camera Roll](https://github.com/kollerlukas/Camera-Roll-Android-App)) i can open files from LFE, and using another file browser ([File Explorer](https://github.com/Raival-e/File-Explorer)), i can open files with Gallery, so it's definitely a compatibility problem between Gallery and Little File Explorer.

**To Reproduce**
1. Download [Little File Explorer](https://martinmimigames.github.io/projects/little-file-explorer)
2. Browse through LFE to find an image
3. Open that image through the Gallery app

**Expected behavior**
Should open and show the picture.

**Smartphone (please complete the following information):**
 - Device: Nokia-TA1157
 - OS: Android 11
 - Version 2.0.0

**Additional context**
I originally reported this issue over at the LFE repository (see [here](https://github.com/martinmimigames/little-file-explorer/issues/66)) but since then, what i suspected was an LFE only problem might be something related to Gallery as well, that involves both apps. In that original issue, i tested it with yet anothe gallery app, Simple Gallery, which worked as well.
I'll tag its developer @martinmimigames (hi) for the sake of communication.

**Comment by IacobIonut01** [comment]
Confirmed
