### ISSUE TITLE
[BUG] Timeline and albums scrolling lags

### ISSUE THREAD

**Issue by ShomyKohai** [IacobIonut01/Gallery#299]
**Describe the bug**

When scrolling through the Timeline or a folder, based on the number of pictures, the app start lagging a lot. 

**To Reproduce**

Scroll through the Timeline with many many pictures. Also tried on a phone with lower specs than the one I've run the tests to confirm. 

**Expected behavior**

A snappy and fast scrolling on mid/low end devices. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei Honor 9
 - OS: Android 13 Lineage OS
 - Version: 2.0.1

**Additional context**

I've been using quickpic before, and wanted to use this app since I find it more appealing for my needs, but compared to how snappy quickpic is, I can't get used to this one. I assume the problem might be that the full picture gets loaded instead of a preview, contrary to how quickpic does.

**Comment by st4ycool** [comment]
Just to be clear, you use application from play store, right? Or you build it yourself?

**Comment by ShomyKohai** [comment]
> Just to be clear, you use application from play store, right? Or you build it yourself?

I use the release from GitHub

**Comment by st4ycool** [comment]
Got you. I am having similar issues with debug builds, they are pretty laggy. But release one seems to be pretty fine, but not perfect, I also have freezes during fast scroll

**Comment by ShomyKohai** [comment]
> Got you. I am having similar issues with debug builds, they are pretty laggy. But release one seems to be pretty fine, but not perfect, I also have freezes during fast scroll

Same, the problems as I said start to appear when scrolling fast, if I give it some time to load the medias of that particular section it does not give a problem doing smaller scrolls. But yeah basically it takes a lot of time to load medias so non high-end devices struggle to catch up.

I am using the latest release No-maps

**Comment by IacobIonut01** [comment]
I'm still working on optimising the media-loading performance for all performance tiers of phones, might take a while until I figure everything out, also right now I'm working on the Edit feature of the app

**Comment by IacobIonut01** [comment]
Starting with 2.1.0-21000 it should be much improved

**Comment by ShomyKohai** [comment]
> Starting with 2.1.0-21000 it should be much improved

Pictured get loaded faster now in the Timeline, but the lag still persists, and it feels worse than before. Tested on the same phone as the one I used when I opened the issue.

Tried uninstalling and reinstalling + clearing cache but the only improvements seem to be the loading times as I said.

**Comment by IacobIonut01** [comment]
Ok thanks for letting me know, I'll continue investigating

**Comment by IacobIonut01** [comment]
@ShomyKohai please try this and see if there's any improvements
[Gallery-2.1.0_46e5acd-release.apk.zip](https://github.com/IacobIonut01/Gallery/files/14164859/Gallery-2.1.0_46e5acd-release.apk.zip)

**Comment by ShomyKohai** [comment]
> @ShomyKohai please try this and see if there's any improvements
> [Gallery-2.1.0_46e5acd-release.apk.zip](https://github.com/IacobIonut01/Gallery/files/14164859/Gallery-2.1.0_46e5acd-release.apk.zip)
> 
> 
> 

There's a slight improvement, but it's still laggy

**Comment by IacobIonut01** [comment]
Thanks! I'll send more builds later on if you want to test as well, would be great!

**Comment by ShomyKohai** [comment]
> Thanks! I'll send more builds later on if you want to test as well, would be great!

sounds great!

**Comment by ArmashOnGit** [comment]
any updates on the issue?

**Comment by IacobIonut01** [comment]
> any updates on the issue? 

You can try the last build from Github actions

**Comment by BluePixel4k** [comment]
I have the same problem with my new Pixel 8. The latest action build reduces the lags only a bit for me.

**Comment by BluePixel4k** [comment]
But the lags only occurs for me in the timeline view and not in the albums.

**Comment by IacobIonut01** [comment]
> I have the same problem with my new Pixel 8. The latest action build reduces the lags only a bit for me.

How many images/videos do you have in total?

**Comment by BluePixel4k** [comment]
@IacobIonut01 around 10800 with 25GB.

**Comment by ShomyKohai** [comment]
> But the lags only occurs for me in the timeline view and not in the albums.

As for the albums, to me it happens mainly when an album has many pictures and videos, something that could mimic the behaviour of the main timeline.

**Comment by ArmashOnGit** [comment]
> > any updates on the issue?
> 
> You can try the last build from Github actions

it still lags unfortunately...

**Comment by ShomyKohai** [comment]
Tried the latest release and the latest github action build, unfortunately it still lags.

**Comment by IacobIonut01** [comment]
The current release is the smoothest (Timeline) I can possibly make with the current Compose state. Regarding the video opening stutter, that is a different issue that I will investigate. Thanks

I will re-open this issue if I will be able to make further improvements to the lag issue
