### ISSUE TITLE
Permissions enhancement: why does your app want to see which networks I’m connected to?

### ISSUE THREAD

**Issue by serrq** [IacobIonut01/Gallery#3]
Please removing the unnecessary permissions.

**Comment by IacobIonut01** [comment]
Sorry for the leftovers permissions. Will be removed asap. They were there from past experiments

**Comment by IacobIonut01** [comment]
![image](https://user-images.githubusercontent.com/19311643/231122974-bc78da69-bad5-4e7f-aa95-940c6895bb33.png)

The current permission list does not require any network information

**Comment by IacobIonut01** [comment]
POST_NOTIFICATIONS will be used later to show notifications regarding moving/copying large amounts of media from an album to another etc
