### ISSUE TITLE
Erase exif metadata 

### ISSUE THREAD

**Issue by Undisputed00x** [IacobIonut01/Gallery#30]
Could make an option to delete any metadata from photos ? 
Also it could even better to be a second option for photos which metadata are erased to be overwriten in place without the need to make a duplicate photo

**Comment by laraib07** [comment]
Also an option where you can share image with or without any metadata would be fine.

**Comment by julianfairfax** [comment]
Please add an option to preserve some data. E.g.: `DATE_TAKEN` (see #107)

**Comment by julianfairfax** [comment]
> Please also add an option to preserve some data. E.g.: `DATE_TAKEN` (see #107)

@IacobIonut01 It doesn't seem like this is included so far?
