### ISSUE TITLE
[Enhancement] Remove internet permission...

### ISSUE THREAD

**Issue by MillionsToOne** [IacobIonut01/Gallery#302]
**Is your feature request related to a problem? Please describe.**
The app currently has internet permissions even though not needed.

**Describe the solution you'd like**
A possible removal of these permissions.

**Describe alternatives you've considered**
No alternatives.

**Additional context**

**Comment by IacobIonut01** [comment]
The Gallery App requires Internet permission in order to download and show a map preview of your current photo location data. However, if this feature is not in your interest, you already have available the 'nomaps' version of it which strips both the map preview and the internet permission requirement.

Please look to previously closed issues before creating a new one. Thanks

**Comment by mdavis-xyz** [comment]
> However, if this feature is not in your interest, you already have available the 'nomaps' version of it which strips both the map preview and the internet permission requirement.

Where is this available?

* The README of this repo does not mention it
* I can't find it in F-droid
* The [F-droid page](https://f-droid.org/packages/com.dot.gallery/) for this app does not contain the substring "map"

**Comment by IacobIonut01** [comment]
> > However, if this feature is not in your interest, you already have available the 'nomaps' version of it which strips both the map preview and the internet permission requirement.
> 
> Where is this available?
> 
> * The README of this repo does not mention it
> * I can't find it in F-droid
> * The [F-droid page](https://f-droid.org/packages/com.dot.gallery/) for this app does not contain the substring "map"

The f Droid version already comes without the map feature and should have the internet permission stripped

**Comment by mdavis-xyz** [comment]
Thanks for the speedy reply. (I wrote PR #759 before I saw your response.)

I was on v4.0.1 (v4.0.2 is not on F-droid yet).
