### ISSUE TITLE
[BUG] Empty Folders Aren't Available to Move Pictures Into

### ISSUE THREAD

**Issue by pwd-github** [IacobIonut01/Gallery#313]
## [Delete before submission] Please use and reproduce the bug on the latest build from Github Actions (Artifacts)
**Describe the bug**

**To Reproduce**
1. Go to another gallery and create a folder
2. Now open this gallery
3. Attempt to move a picture to the new folder

**Expected behavior**
Empty folders should be available

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - OS: Android 14
 - Version 2.0.0

**Additional context**

**Comment by IacobIonut01** [comment]
Can't reproduce this.

Make sure you are creating albums under storage/Pictures/ or storage/DCIM/

This app doesn't use full storage access (less permissions) so the only location you can create albums for the time being are under the folders from above.

I will also add full storage access for those who want this feature

**Comment by IacobIonut01** [comment]
Close due to inactivity
