### ISSUE TITLE
[Enhancement] improve ignored albums functionality to ignored directories instead (directories can have subdirectories)

### ISSUE THREAD

**Issue by namesarebloat** [IacobIonut01/Gallery#335]
**Is your feature request related to a problem? Please describe.**
I have my music library organised by ~/music/artist/album and in every album directory there's a cover.png. In the gallery these hundreds of album covers drown out the images I actually want to look at. 

**Describe the solution you'd like**

The current ignored albums functionality only allows me to add each ~/music/artist/album to the ignored albums, which would take forever to manually add. I'd like to just hide everything inside ~/music and its subdirectories.

**Describe alternatives you've considered**

Adding 600+ album covers to the ignore list manually, one by one

**Additional context**

**Comment by IacobIonut01** [comment]
The app is using MediaStore API's, so it doesn't have any access to folders or the filesystem itself. To add this functionality it would require a more permissive approach which is adding a new permission that will grant the app full access to the internal storage.
This permission will also be used for copying/moving media to restricted folders as well (Android/media/*, outside of DCIM or Pictures)

As a temporary solution for you is to create a '.nomedia' file on your main album (it might work for inner albums as well)

**Comment by Bytezz** [comment]
The app does know file path, so it can be used to check whether an image is inside an ignored directory or in one of its subdirectories.

<details>
<summary>Screenshot</summary>

![screenshot](https://github.com/IacobIonut01/Gallery/assets/25850701/abe3817e-377b-4a1c-9599-fbe1beebea8d)
</details>

**Comment by onnyyonn** [comment]
I have added a .nomedia file in a directory, and it has several subdirectories with images. The subdirectories are still appearing as albums in the gallery.

**Comment by IacobIonut01** [comment]
I've forgotten to update this issue, but the feature is already available in the latest nightly under Ignored Albums. You can create a regex pattern to target multiple albums/folders at the same time

**Comment by onnyyonn** [comment]
> I have added a .nomedia file in a directory, and it has several subdirectories with images. The subdirectories are still appearing as albums in the gallery.

Updated to version 3.0.0, and tested the .nomedia method. This time, All subdirectories were excluded, as expected.

> I just noticed when you use the app as a file picker (for example in system settings > wallpaper & style > change wallpaper > my photos > complete action using gallery), the list of albums at the top does not filter out ignored albums

With the .nomedia method, they don't appear on the file picker either.
