### ISSUE TITLE
[BUG] java.lang.RuntimeException: Canvas: trying to draw too large bitmap.

### ISSUE THREAD

**Issue by ErrrorMaxx** [IacobIonut01/Gallery#336]
**Describe the bug**
My phone can took 9MB+ photos, which I can't edit in this app (app crashes)

**To Reproduce**
1. Get large photo
2. Try to edit it in app

**Expected behavior**
App not crashes and I can edit photo

**Smartphone:**
 - Device: TECNO Camon 20 Pro 5G
 - OS: Android 13
 - Version 2.1.0 (from actions)

**Additional context**
java.lang.RuntimeException: Canvas: trying to draw too large(254803968bytes) bitmap.

**Comment by inferenceus** [comment]
I have the same issue; app crashes when attempting to edit a 50 MP JPG image.

Google Pixel 8 Pro with 12 GiB memory.

**Comment by IacobIonut01** [comment]
Will be resolved soon while also adding the support for subsampling images (loading the full resolution)

**Comment by inferenceus** [comment]
> Will be resolved soon while also adding the support for subsampling images (loading the full resolution)

Great. Thanks.

**Comment by IacobIonut01** [comment]
Fixed in https://github.com/IacobIonut01/Gallery/commit/450a724909d1bf1ce3f00f4e93205a8350cba8c3

**Comment by inferenceus** [comment]
> Fixed in [450a724](https://github.com/IacobIonut01/Gallery/commit/450a724909d1bf1ce3f00f4e93205a8350cba8c3)

Thanks a lot.
