### ISSUE TITLE
[Enhancement] Allow Start-up View Choice

### ISSUE THREAD

**Issue by inferenceus** [IacobIonut01/Gallery#341]
**Is your feature request related to a problem? Please describe.**
From what I've experienced, Gallery always starts (at least, from cold-start) in the individual image and video view. It would be nice to have an option to have the app start up in folder view.

**Describe the solution you'd like**
A simple setting in app settings which allows choice of default view.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by IacobIonut01** [comment]
Already done

**Comment by inferenceus** [comment]
> Already done

Which commit/version is this available in?

**Comment by IacobIonut01** [comment]
Thanks!
