### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by M00NJ** [IacobIonut01/Gallery#342]
I'm really impressed by how well designed and executed Gallery is as a project and already recommended it to quite a few people. There are some small ui changes I'd like to suggest though, mainly regarding the three dot menu. 

Currently the menu opens a bottom sheet that houses navigation destinations (`Trash`, `Favorites`) as well as actions (`Select all)`, which you usually don't want to mix. 

![Bottom Sheet](https://github.com/IacobIonut01/Gallery/assets/82398591/ffaf7f0c-a615-454f-9dcd-4264fe5b1d54)

Destinations should also ideally be reachable through navigation components only. Therefore I suggest moving `Trash` to the navigation bar. 

![Navigation Bar](https://github.com/IacobIonut01/Gallery/assets/82398591/bfb1d937-6923-45a7-a184-fcb7a6663cc2)

`Trash` is a frequently used item. Moving it to the navbar makes it more accessible. Also the Material 3 guidelines suggest to use navbars only for three or more destinations which would be fix by this as well. Screenshot from material.io:

![Screenshot from 2024-02-21 13-51-09](https://github.com/IacobIonut01/Gallery/assets/82398591/35c4f185-f116-4cc4-94e9-604c8dd08f35)

Also imo it makes sense for `Favorites` to be an album, since it groups together pictures selected by the user. So I suggest moving it to the album screen. The album card could be overlayed with a heart icon to make it stand out more from the other albums.

![Screenshot from 2024-02-21 13-44-15](https://github.com/IacobIonut01/Gallery/assets/82398591/2d915a67-1c24-4dae-9990-3f9d2ca783b6)

These two changes (`Trash` -> navbar & `Favorites` -> Albums) would also make the two buttons at the top in the album screen obsolete.

![Buttons](https://github.com/IacobIonut01/Gallery/assets/82398591/476c368b-a1eb-430c-b5eb-c14513150281)

They could be removed to free up more screen space for the albums and make the ui cleaner. Because of their placement at the top of the screen they aren't the most comfortable to reach anyways. 

![Albums](https://github.com/IacobIonut01/Gallery/assets/82398591/34cbb445-6c2b-429a-ab39-78ef1acc9332)

This would leave only two items left is the bottom sheet (`Select all` & `Settings`). I'd suggest splitting them apart and adding them directly to the top bar, which would make it only one click to `Select all` or go to the `Settings`.

![Top Bar](https://github.com/IacobIonut01/Gallery/assets/82398591/0002684e-7b61-4e82-9113-75a421bdb1a0)

Alternatively a popover menu could work here as well, but would require more input.

I hope some of the suggestions are interesting to you and that the mock-ups helped to visualize what I was talking about :)

**Comment by IacobIonut01** [comment]
Hi, thanks for the suggestions!

Currently the navigation bar contains only 2 items because the 3rd one is being worked on; it's gonna be the place to see sorted media by location, content, accessing the Private Album and there will be moved the Favorites and Trash buttons.
