### ISSUE TITLE
[BUG] Videos open but cannot be played through file manager

### ISSUE THREAD

**Issue by Cwpute** [IacobIonut01/Gallery#348]
**Describe the bug**
You can open videos from the file manager but they aren't played: instead you're only left with a single frame from the video, shown as a picture.
Opening the same video from gallery app itself makes it work as expected.

**To Reproduce**
1. Go to your file manager (i'm using LittleFileExplorer)
2. Open any video
3. See how the Gallery seemingly interprets it as an image

As opened through the Gallery:
![Screenshot_20240224-155434](https://github.com/IacobIonut01/Gallery/assets/80604512/2690ccfe-693c-4394-97a9-5316758a2966)

As opened through the file manager:
![Screenshot_20240224-155403](https://github.com/IacobIonut01/Gallery/assets/80604512/d40a9aee-a540-4fd5-8c53-24f186d464d0)

**Expected behavior**
Gallery should recognize it as a video and provide the corresponding to control its playstate.

**Smartphone (please complete the following information):**
 - Device: Nokia TA-1157
 - OS: Android 11
 - Version 2.1.0

**Additional context:**
Might be linked to previously resolved #340

**Comment by IacobIonut01** [comment]
Fixed in #340
