### ISSUE TITLE
SVGs are pre-viewable, but not viewable

### ISSUE THREAD

**Issue by julianfairfax** [IacobIonut01/Gallery#35]
It seems SVGs can be correctly pre-viewed, but not correctly viewed.

Example:

Photos/albums pre-view:
![IMG_20230419_224540](https://user-images.githubusercontent.com/43753131/233196096-74d2edea-f9f1-4157-9241-cc7366ce5f68.jpg)

View of first image:
![Screenshot_20230419-224430](https://user-images.githubusercontent.com/43753131/233196508-458a63cf-9674-4299-be01-2248874ace6d.png)

View of second image:
![Screenshot_20230419-224434](https://user-images.githubusercontent.com/43753131/233196696-483aaab6-8d00-42df-a601-7875b19ed27a.png)

**Comment by IacobIonut01** [comment]
There's a tint applied for svgs on view, that was intended for
monochromatic svgs like icons to be tinted from Black to White in order to
be visible, but I guess it's not worth it as the colored svgs are broken.

I will revert the tint change asap

**Comment by IacobIonut01** [comment]
The fix is pushed to the repo, you can download the apk manually from Github Actions or wait for the weekly release
