### ISSUE TITLE
[BUG] App closes the photo on switching screen orientation

### ISSUE THREAD

**Issue by Snehargho123** [IacobIonut01/Gallery#350]
**Describe the bug**
Photos dont switch orientation on the go. I need to open the photo in the orientation I desire to view it in. If I switch orientation while viewing the photo then the app closes the photo and takes me to the all photos list.

**To Reproduce**
1. Open any photo
2. Switch screen orientation (portrait to landscape in my case
3. The photo is closed and I am taken to the all photos screen. This time the all photos screen opens with the orientation I switched to. Now keeping this orientation, I have to find and open the photo again

**Expected behavior**
I open and photo in full screen and if I switch screen orientation, the photo should also remain open an switch orientations

**Smartphone (please complete the following information):**
 - Device: [Galaxy A34]
 - OS: [Android 14]
 - Version [2.1.0]

**Additional context**
This is standard behaviour on any other app be it gallery or something else. Hence I feel like this is a bug. Kindly look into it. It does not seem very complex. I hope it won't take a toll on you to fix it. If you feel like it, please tell me exactly what to do and I shall help you make the changes. Thank you for actively maintaining this beautiful app.

**Comment by IacobIonut01** [comment]
Please install the latest version from Github Actions and check again, I've tried on my end and I can't seem to reproduce this bug

**Comment by Snehargho123** [comment]
I am very thankful for the reply. I reinstalled the app and it works now. Also opening from the file manager did not work for me at all despite the latest version but the same reinstall that fixed the orientation thing, also fixed the file manager thing. I am closing this issue. Thanks a lot!

**Comment by Sockolet** [comment]
This is happening to also. I'm running latest version 21040 from F-Droid. It happened in previous version as well.
Mobile is Samsung Galaxy S20 FE, running Android 14 with latest patches.

**Comment by Melr0k** [comment]
I have the exact same issue, even installing the latest version 2.1.2-21204, with Android 13 on a Motorola edge 40 neo.

**Comment by ahormann** [comment]
I had the same Issue with 2.1.2.
I downgraded to 2.1.1 and that fixed it for now, but maybe it was the reinstalling rather than the Version change.
Also Android 14 and a Pixel 7a.

**Comment by IacobIonut01** [comment]
I can't seem to reproduce the bug, but I will still try to find some possible causes, if you manage to make a reliable way to reproduce it please let me know
