### ISSUE TITLE
[Enhancement] Editor: Drawing

### ISSUE THREAD

**Issue by BigPebble123** [IacobIonut01/Gallery#351]
**Is your feature request related to a problem? Please describe.**
I often find myself wanting to blur something on a photo or add my own annotations to my photos. Currently, the editor only allows you to crop, rotate, mirror and change the color of a photo. There is no built-in function to draw directly on photos, and this limitation is frustrating because I have to use an external app to do it.

**Describe the solution you'd like**
I would like the gallery app to include a drawing feature in its photo editor. This would enable users to draw or write on their photos.

**Describe alternatives you've considered**
I'm currently using an third-party app for this.

**Additional context**
The drawing tool should be intuitive and user-friendly, with options for different colors, brush sizes, and perhaps even basic shapes.

**Comment by IacobIonut01** [comment]
Hi, thanks for your suggestions! I'm already planning on adding this, but it's good to be specified in a new issue.

**Comment by mon-jai** [comment]
Maybe it is done?

**Comment by IacobIonut01** [comment]
Yes it is
