### ISSUE TITLE
Installation error, version 1.0.1 and 1.0.2

### ISSUE THREAD

**Issue by franco27** [IacobIonut01/Gallery#36]
Hello

After downloading the APK file from Github, when I open the installer file with Android, there is an error message.

The error message is displayed immediately and I don't get the installation progress window.

I am attaching a screenshot of the error message, here is the English translation "a problem occurred while parsing the package".

**Comment by IacobIonut01** [comment]
Make sure your phone runs Android 11 or higher.

**Comment by franco27** [comment]
I give you my system information from my phone 
Xiaomi Redmi 8 
Android Version 10 Android 10 
MIUI   V12.5.2.0.QCNEUXM

Architecture 64-bit

Instruction sets
arm64-v8a armeabi-v7a armeabi Qualcomm®
Snapdragon™ 439

CPU  4 x Cortex-A53
Cores 8
RAM size 4 GB

![IMG_20230420_160455](https://user-images.githubusercontent.com/31793920/233396492-3495b047-dd39-4215-8fec-6a14e793dcb2.jpg)

**Comment by franco27** [comment]
So I can't use your app then.... I'm with Android 10.

thank you for your reply

**Comment by IacobIonut01** [comment]
Not at this particular moment. This limitation is set to ensure the full
set of features this app has. On Android 10 and lower things like "Mark as
Favorite" or "Trash Bin" are not available
