### ISSUE TITLE
[Enhancement] Please use Semantic Versioning

### ISSUE THREAD

**Issue by ColorfulRhino** [IacobIonut01/Gallery#370]
Hello!

Unfortunately, the versioning for this app so far is quite unintuitive. The same version seemingly gets released multiple times, but changes have been made.

Example:

![](https://github.com/IacobIonut01/Gallery/assets/131405023/140d82a2-07ef-403e-9f89-8c4535d719ec)

---

**Please always use Sematic Versioning** https://semver.org/ which is the defacto standard for software development.
- Multiple bugfixes or even just a tiny tiny bugfix? --> increase from 2.1.0 to 2.1.1
- New features? --> increase from 2.1.x to 2.2.0
- Major new release with potentially breaking changes (like exported configs not compatible with import in new version)? --> increase from 2.x.y to 3.0.0

Thank you!

**Comment by IacobIonut01** [comment]
Thanks for pointing it out. I'll make proper version changes from now then.
