### ISSUE TITLE
[NOT SUPPORTED] "An error occurred while parsing the package"

### ISSUE THREAD

**Issue by MarddleDoo12** [IacobIonut01/Gallery#376]
Well, I have a 32-bit Motorola G6 play (armv7) with Android 9.0, the application is not compatible with my phone, I wanted to know if there is 32-bit compatibility, and if not, could you please add it?

If this counts as a suggestion, let me know and I'll change it.
![Screenshot_20240324-033423](https://github.com/IacobIonut01/Gallery/assets/113211768/0a4b3b39-b6e9-4c77-8c9e-400c51266e66)

**Comment by IacobIonut01** [comment]
I suggest reading the Frequent Questions on the README page.
