### ISSUE TITLE
[Enhancement] Custom grid size

### ISSUE THREAD

**Issue by Donkey-Doug** [IacobIonut01/Gallery#387]
**Is your feature request related to a problem? Please describe.**
The image previews in the grid are too small.

**Describe the solution you'd like**
A customizable grid size.

**Describe alternatives you've considered**
Holding the phone closer to my face.

**Additional context**
Perhaps make it possible to adjust the grid size by doing a zoom gesture?

**Comment by IacobIonut01** [comment]
Already done.
