### ISSUE TITLE
Enhancement: The ability to pin certain albums to the top of the list.

### ISSUE THREAD

**Issue by ViktorKahu** [IacobIonut01/Gallery#4]
Enhancement: The ability to pin certain albums to the top of the list.

**Comment by IacobIonut01** [comment]
Thanks for the suggestion. I'll make sure it's included in the next update

**Comment by IacobIonut01** [comment]
Thanks for the suggestion. I'll make sure it's included in the next update

**Comment by ViktorKahu** [comment]
Only to simply hide from the list is my initial request.

**Comment by IacobIonut01** [comment]
Added
[789d34](https://github.com/IacobIonut01/Gallery/commit/789d3476fe5466d9f49b4191c9611f1cc77e3c3f)
