### ISSUE TITLE
Hidden folders[Enhancement]

### ISSUE THREAD

**Issue by shockergit** [IacobIonut01/Gallery#402]
Please add an option to show hidden media folders and files

**Comment by mariuszeek** [comment]
Was about to ask this. I have recently bought this app and it is only missing feature for this app be perfect, some kind of tab for hidden elements.

**Comment by Undisputed00x** [comment]
Using latest nightly https://github.com/IacobIonut01/Gallery/releases/tag/3.0.1-30123.
Still media within hidden folders are not shown in albums section.

**Comment by IacobIonut01** [comment]
This will not be done. The app uses the Media Store as a source of media and that doesn't scan any hidden or dot named files.
