### ISSUE TITLE
[BUG] Duplicate confirmation for deleting/moving to trash

### ISSUE THREAD

**Issue by Captn138** [IacobIonut01/Gallery#405]
**Describe the bug**
When deleting a picture or moving it to trash, I am asked to confirm twice and I don't see the point of it.

**To Reproduce**
1. Open a picture
2. Click on the trash icon
3. "Moving to trash" click "Confirm"
4. See problem: "Allow gallery to move this photo to trash"?" click "Allow"

**Expected behavior**
When confirming to delete the picture the first time, I shouldn't be asked a second time

**Screenshots**
![Screenshot_20240425-114837_Gallery.png](https://github.com/IacobIonut01/Gallery/assets/25801033/01d14988-b38b-427b-bd0c-7c0f29d0564d)

![Screenshot_20240425-114841_Media Storage.png](https://github.com/IacobIonut01/Gallery/assets/25801033/d090bb58-85bb-4af5-93f8-5352c7ad4a6a)

**Smartphone (please complete the following information):**
 - Device: Fair Phone 5
 - OS: /e/OS 1.21 (Android 13)
 - Version: 2.1.2

**Additional context**
The application has the permissions to access my pictures as seen below

![Screenshot_20240425-115047_Permission controller.png](https://github.com/IacobIonut01/Gallery/assets/25801033/fc8d017a-ab04-4def-8a77-80e0876c6396)

**Comment by IacobIonut01** [comment]
THIS IS NOT A BUG!

This has been explained at the setup of the app, in order to avoid the second confirmation you need to make the app a Media Manager (Settings -> Apps -> Special app access -> Media management apps). You can quickly do that from the first install of the app at the setup wizard

**Comment by Captn138** [comment]
Thanks a lot !

**Comment by Riksu9000** [comment]
Can you detect if the permission is not given, and skip one of the confirmations? Or maybe just rely on the system confirmation?
