### ISSUE TITLE
[BUG] Some photos have large frames

### ISSUE THREAD

**Issue by SpiritOTHawk** [IacobIonut01/Gallery#409]
**Describe the bug**
Some photos have large frames, unlike normal ones
![Screenshot_20240501-101412](https://github.com/IacobIonut01/Gallery/assets/76490476/0444e294-becb-4c7d-a1a8-69e3d89f0fae)

**To Reproduce**
1. Download this photo (maybe) 
![DSC_5047](https://github.com/IacobIonut01/Gallery/assets/76490476/3327f9c8-b47f-4d88-af32-648930884b41)
2. Open gallery

**Expected behavior**
![Screenshot_20240501-101401](https://github.com/IacobIonut01/Gallery/assets/76490476/c1fe8e82-2786-440d-87c3-b4e193ad1423)

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 1
 - OS: Android 14 / nothingOS 2.5.5
 - Version 2.1.2

**Comment by IacobIonut01** [comment]
Fixed, will be available in the nightly soon
