### ISSUE TITLE
Lag while scrolling 

### ISSUE THREAD

**Issue by Sureshgorai25** [IacobIonut01/Gallery#41]
The homepage/album page still lags while scrolling, it got 3rd update still same lag.
Some features r missing but it's still good, it only needs optimisation, hope u will fix lag soon

**Comment by IacobIonut01** [comment]
Specify device and android version

**Comment by Sureshgorai25** [comment]
Device- Realme 3 Model RMX1825
Android version 13

**Comment by IacobIonut01** [comment]
I've tested with multiple SOCs (sm662, sm720, gs101 etc) and Storage types (emmc5.1, ufs1.x, 2.x etc) and I could a huge improvement in the smoothness with the 1.0.3 update.
Tests were made with media size of over 2000 items. It would be great if you can provide a systemtrace while using the app so I can further investigate the lag issue

**Comment by Sureshgorai25** [comment]
I wish I can, but ig in Android 13, system tracing is removed from developer option and I don't have pc/other device.

**Comment by IacobIonut01** [comment]
![Screenshot_20230424-113849.png](https://user-images.githubusercontent.com/19311643/233944231-a6bd8c7b-9251-4dd7-a32b-94a1d0798ff8.png)

It's still available in Developer Settings

**Comment by IacobIonut01** [comment]
Yes

**Comment by Sureshgorai25** [comment]
/

**Comment by IacobIonut01** [comment]
Closed for inactivity
