### ISSUE TITLE
[Enhancement] Ignore directories and all child objects by path

### ISSUE THREAD

**Issue by foundObjects** [IacobIonut01/Gallery#411]
**Is your feature request related to a problem? Please describe.**
Album view picks up an entire comic collection on my SD card (thousands of subdirectories containing individual comic issues or graphic novels) that I'd like to ignore all at once. At present I need to select every one of those as individual albums and ignore them by hand.

**Describe the solution you'd like**
I'd like to be able to add paths to ignore and have all subdirectories further down the filesystem tree from that point ignored as well. Eg: if I ignore sdcard://comics/ the gallery should skip that portion of the tree (everything beneath that path.) 

**Describe alternatives you've considered**
I could manually ignore about 2500 albums

**Additional context**
n/a

**Comment by IacobIonut01** [comment]
It will be available in the next release along with Vault (encrypted media)

**Comment by foundObjects** [comment]
Awesome, thanks!

**Comment by Feuerswut** [comment]
PLEASE YES PLEASE

**Comment by IacobIonut01** [comment]
Sorry to update so lately, but this is already available with the 'Ignored Albums' Overhaul. Create a regex pattern to match all your targeted albums and should be filtered automatically (even new ones)

**Comment by foundObjects** [comment]
> Sorry to update so lately, but this is already available with the 'Ignored Albums' Overhaul. Create a regex pattern to match all your targeted albums and should be filtered automatically (even new ones)

No worries, thanks for the feature - it's exactly what I needed.

Cheers!
