### ISSUE TITLE
app return to home when rotate in any folder

### ISSUE THREAD

**Issue by krzemyczek** [IacobIonut01/Gallery#413]
**Describe the bug**
When I want to watch video and then rotate phone, app return to main screen. The same if I'm in any folder

**To Reproduce**
1. Go to any folder
2. Rotate phone
3. See error

**Expected behavior**
The same place where I was. This is. If I'm watching video I want to watch it in landscape mode

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6a
 - OS: GrapheneOS 14 (AP1A.240505.004)
 - Version 2.1.2

**Comment by Guizp31** [comment]
Same behaviour when viewing photos then rotating the phone: the app returns on main screen instead of rotate the screen / displayed photo.

- Device: Fairphone 4
- OS: Android 13 (FP4.TP2G.C.0119.20240509)
- Version 2.1.2 (Play Store)

**Comment by krzemyczek** [comment]
seems to be fixed in 3.0.0
