### ISSUE TITLE
[Enhancement] Option to stop the navbar and top bar from coming back automatically.

### ISSUE THREAD

**Issue by Gu57avo** [IacobIonut01/Gallery#419]
**Is your feature request related to a problem? Please describe.**
I really like the app, but it's really annoying to me that the navbar and top bar come back on their own.

**Describe the solution you'd like**
An option to have both bars only come back on a swipe up, and hide on swipe down (like in Google photos)

**Describe alternatives you've considered**
I would be okay with having the bars be permanently visible too.

**Additional context**
My biggest issue is that by hiding the bars you make some content visible that you cannot actually access, like if I see a picture I want to click on at the bottom of my screen and I stop scrolling, that picture is now unaccessible, I have to scroll down more so that the bars don't cover my picture when they inevitably come back.
Also I'm pretty sure it's bad design to have content that you think is clickable suddenly obstructed by something without input from the user.

I love everything else about the app though 👌

**Comment by IacobIonut01** [comment]
This is available in the latest release
