### ISSUE TITLE
[BUG] Videos are stretched

### ISSUE THREAD

**Issue by pasqchia** [IacobIonut01/Gallery#420]
**Describe the bug**
Played videos look stretched. None of them show as they should, rather they all look so stretched to the point that a part of the image is out of the screen. Happens on both landscape and portrait videos. Images look as they should.

**To Reproduce**
1. Play a video.
2. It is stretched.

**Expected behavior**
It shouldn't look stretched.

**Screenshots**
![Screenshot_20240617-170334.png](https://github.com/IacobIonut01/Gallery/assets/109210562/0affe152-6639-48d8-aace-03d0a48ab27a)
👆 What it looks like:

![Screenshot_20240617-170405.png](https://github.com/IacobIonut01/Gallery/assets/109210562/4c830e10-0744-4b55-b57f-cb422381aa7b)
👆 What it should look like:

**Smartphone:**
 - Device: Google Pixel 7
 - OS: Android 14 (GrapheneOS, no GApps)
 - Version: 2.1.2, both from F-Droid and GitHub

**Comment by Mondei1** [comment]
I can actually confirm the same issue. Also running GrapheneOS on a Pixel 6. But I doubt that this is a platform issue.

**Comment by Capta1nT0ad** [comment]
Can reproduce on a Pixel 7a running the stock/original ROM. When in landscape mode, the video in stretches but is partially translated right to an area off the screen. I wonder if this issue is isolated to Pixel devices considering the lack of reports while the issue more or less makes videos unplayable.

**Comment by Turtlecute33** [comment]
Same issue of pixel 7 with Graphene OS

**Comment by IacobIonut01** [comment]
Already fixed in nightly
