### ISSUE TITLE
Zoomed-in photos still pixelated after 1.0.3 update.

### ISSUE THREAD

**Issue by sledgehammer0019** [IacobIonut01/Gallery#43]
![IMG_20230425_164211_669.jpg](https://user-images.githubusercontent.com/47625406/234223329-ca0ad5e5-ab60-4dbd-a658-4ebf715ffbd1.jpg)

For comparison: 
The above photo is from the latest 1.0.3 update of the Gallery app.

The photo below is from the Gallery app made by Google.

**Comment by IacobIonut01** [comment]
![Screenshot_20230425-123741.png](https://user-images.githubusercontent.com/19311643/234237526-16d534bb-4c03-494f-965b-5c04cbb9b25a.png)

![Screenshot_20230425-123727.png](https://user-images.githubusercontent.com/19311643/234237527-bab80bfa-bd4d-49a3-81c8-9caa91832ccf.png)

First is Google Photos, Last is Gallery after the fix
