### ISSUE TITLE
[BUG] RAW/DNG thumbnails are shown, but not visible in image viewer.

### ISSUE THREAD

**Issue by tundruh** [IacobIonut01/Gallery#431]
**Describe the Bug**
RAW/DNG images will show up in Gallery, and the thumbnails/previews are visible. However, viewing the RAW/DNG files results in a blank or blurry background depending on settings. Metadata is still visible (date, time, etc.) and details will still work, but no image.

**To Reproduce**
1. Take a RAW/DNG photo using Open Camera
2. Navigate to Gallery after taking photo
3. See preview/thumbnail
4. Open image viewer
5. Blank or blurry background, no image present

**Expected behavior**
Opening a RAW/DNG in the viewer will show the full image, identical to the JPG/other file types.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8
 - OS: Android 14 / GrapheneOS
 - Version 2024071600

**Additional context**
Other gallery apps (i.e. Aves Libre) show the RAW/DNG thumbnail as well as in the image viewer.

**Comment by IacobIonut01** [comment]
In my case I can see the RAW image😅, but not correctly. I will investigate but for sure it is an issue with the Subsampling Image library
![Screenshot_20240718-111944.png](https://github.com/user-attachments/assets/c6e65a9f-18a3-49d4-a950-00c60e6db323)

**Comment by IacobIonut01** [comment]
In my case I can see the RAW image😅, but not correctly. I will investigate but for sure it is an issue with the Subsampling Image library
![Screenshot_20240718-111944.png](https://github.com/user-attachments/assets/c6e65a9f-18a3-49d4-a950-00c60e6db323)

    Can you provide a link to a test image?

**Comment by IacobIonut01** [comment]
> @IacobIonut01 Just to clarify, you need a comparison to a working test image vs RAW?

Nah, just send over an example RAW image that causes you the problem

**Comment by tundruh** [comment]
> 
> Nah, just send over an example RAW image that causes you the problem

Sure thing. 

I just used this first DNG example from this old blog site.

https://www.kenrockwell.com/leica/m9/sample-photos-3.htm

And the following are what I see when previewing, opening, and "focusing" (when tapping again within the viewer and the metadata and info hide temporarily).

![Screenshot_20240718-101116.png](https://github.com/user-attachments/assets/1f2aaabd-433b-4192-8522-4d5805c715fc)

![Screenshot_20240718-101119.png](https://github.com/user-attachments/assets/08d96933-4cd8-49ab-8d46-6323789c67f0)

![Screenshot_20240718-101124.png](https://github.com/user-attachments/assets/a831d877-178f-4e14-82d1-aa05f5cde183)

FYI, I also just updated to the latest nightly build and still have this issue.

**Comment by IacobIonut01** [comment]
> > 
> > Nah, just send over an example RAW image that causes you the problem
> 
> Sure thing. 
> 
> I just used this first DNG example from this old blog site.
> 
> https://www.kenrockwell.com/leica/m9/sample-photos-3.htm
> 
> And the following are what I see when previewing, opening, and "focusing" (when tapping again within the viewer and the metadata and info hide temporarily).
> 
> ![Screenshot_20240718-101116.png](https://github.com/user-attachments/assets/1f2aaabd-433b-4192-8522-4d5805c715fc)
> 
> ![Screenshot_20240718-101119.png](https://github.com/user-attachments/assets/08d96933-4cd8-49ab-8d46-6323789c67f0)
> 
> ![Screenshot_20240718-101124.png](https://github.com/user-attachments/assets/a831d877-178f-4e14-82d1-aa05f5cde183)
> 
> FYI, I also just updated to the latest nightly build and still have this issue.

Thanks, I'll get back with the fix

**Comment by tundruh** [comment]
@IacobIonut01 Just downloaded the nightly from 4 Aug, and RAW is working perfectly!

Thanks for addressing the issue, now I can delete my other gallery apps entirely. Great work, looking forward to what else you accomplish. 👍🏽

**Comment by IacobIonut01** [comment]
Thanks! You can close the issue now if all is good
