### ISSUE TITLE
[BUG] App Crashes when trying to edit 8K photos.

### ISSUE THREAD

**Issue by ShadowOfPripyat** [IacobIonut01/Gallery#439]
**Describe the bug**
The app crashes after trying to edit a picture that has a resolution of 8K (48.9 MP • 8160 x 6144 px).

**To Reproduce**
1. Open any photo that has a resolution of 8K pixels.
2. Click on 'edit' on the bar below (between 'favorite' and 'delete'
3. The editor opens with black screen and then app crashes.

**Expected behavior**
Being able to use the editor with ultra high resolutions without any issue.

**Screenshots**
Not necessary to describe the issue.

**Smartphone (please complete the following information):**
 - Device: [Nothing Phone 1]
 - OS: [e.g. Android 13]
 - App Version [ 2.1.2] (From F-droid)

**Additional context**
None.

**Comment by IacobIonut01** [comment]
Thanks for your report, but currently the Editor is having a major revamp which also fixes this issue. I'll close it after the new Editor is out.

Thanks!
