### ISSUE TITLE
[Bug] Map isn't loading

### ISSUE THREAD

**Issue by pabloscloud** [IacobIonut01/Gallery#45]
When I disable internet, the map isn't loading obviously. Before a text was shown that there is no internet connection. 

I guess after you changed it from the string to coordinates it messed it up. Idk

![d4f1f6db-7cce-4198-964e-23c58bbc8967](https://user-images.githubusercontent.com/93644977/234442243-3491fdbe-3872-4bfc-ae8a-d6fab242e377.png)

**Comment by pabloscloud** [comment]
This is low priority imho. I can still see the map if I click on it. I just reported it as it still a bug I'd say

**Comment by pabloscloud** [comment]
Where did you download it?

**Comment by pabloscloud** [comment]
I've just tested it and I can confirm this is the case for me as well. I'm on a Pixel 7 with GrapheneOS. I'm running the latest version available from GitHub releases.

**Comment by IacobIonut01** [comment]
It has been fixed already in a previous commit, check latest build from Github Actions
