### ISSUE TITLE
[BUG] Can't install from f droid via droid ify

### ISSUE THREAD

**Issue by hasanelfalakiy** [IacobIonut01/Gallery#456]
**Describe the bug**
can't install from droid ify app 

**Expected behavior**
can install

**Screenshots**
https://github.com/user-attachments/assets/c5a238b7-3de5-490c-9dc3-c0a1f66f2a3b

**Smartphone (please complete the following information):**
 - Device: [Vivo Y15 2019]
 - OS: [Android 11]
 - Version [2.0.0]

**Comment by IacobIonut01** [comment]
Redirect your issue to the droid-ify app, not the actual Gallery app. I'm not responsible how the droid-ify is handling the f-droid repo downloads and actually any part of the droid-ify app. So if there's a bug in THAT app, then you should open an issue there.
