### ISSUE TITLE
[BUG] APP crashes

### ISSUE THREAD

**Issue by Stzyxh** [IacobIonut01/Gallery#457]
**Describe the bug**
When i try ro open the gallery it crashes.

**To Reproduce**
1. open the 'app
2

**Expected behavior**
Should crah
**Screenshots**
https://github.com/user-attachments/assets/52b5d4c4-bd62-4c3d-9b38-4e13a5746c1f

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android 13
 - Version 3.00 also in beta for 3.01

**Additional context**

**Comment by tomaszk8266** [comment]
Clear data and then it should work.
