### ISSUE TITLE
[BUG] Videos get interrupted by the screen getting into sleep mode.

### ISSUE THREAD

**Issue by Cwpute** [IacobIonut01/Gallery#460]
**Describe the bug**
Sometimes when watching videos with Gallery, the playback keeps getting interrupted by the phone getting into sleep mode. I'm watching the video like normal, but suddenly, the phone's screen turns to black, then shows the phone's lock screen, with the time, date and notifications, just like i inadvertedly pressed the power button to put it into sleep mode. Once i unlock the phone, the video is still there in fullscreen, paused, and i can resume the playback just fine… but this will happen again in a minute or so.

**To Reproduce**
I can't seem to find a pattern for when this bug occurs… i'll update this issue with any information i can come across.

**Expected behavior**
The video should play without getting interrupted.

**Smartphone (please complete the following information):**
 - Device: Nokia TA-something
 - OS: Android 11
 - Version 2.1.2

**Comment by IacobIonut01** [comment]
It has been fixed before in the nightly.

Check out the new nightly 3.0.1-30101 that is going to be released in a bit

**Comment by Cwpute** [comment]
i'm on a metered connection so i won't, but i will definitely get back to you if this happens to still occur in later official releases

**Comment by IacobIonut01** [comment]
> i'm on a metered connection so i won't, but i will definitely get back to you if this happens to still occur in later official releases

The next nightly will have separated ABI apks which will be marginally smaller in size btw
