### ISSUE TITLE
[BUG] Photo info, black screen

### ISSUE THREAD

**Issue by turmoil-preshow** [IacobIonut01/Gallery#469]
**Describe the bug**
You can trigger a black screen (or partial black screen if the photo doesn't have a geotag)

**To Reproduce**

1. Open a photo on full screen
2. Click in the middle of the photo to hide the UI, 
3. Before it fully hides, click on the info icon on the top right
4. The menu that opens on the bottom will be invisible, but still intractable
5. you can go back with the back gesture

**Expected behavior**
The info icon shouldn't be clickable when transitioning to hidden

**Smartphone:**
 - Device: Google Pixel 8
 - OS: Android 14
 - Version 3.0.0-30033
 
**Video attached**
https://github.com/user-attachments/assets/dbfea793-18d9-4b3c-ba13-de7d9e45e9ef

**Comment by IacobIonut01** [comment]
Fixed in 3.0.1-30102 nightly release
