### ISSUE TITLE
Enormous app size

### ISSUE THREAD

**Issue by rafnov** [IacobIonut01/Gallery#470]
Screenshots should tell all, but here is my comment.
I've synced Droid-ify and checked f-droid.org. Both show that Gallery app has grown... 5 times bigger. Wait, what?...
Just check it yourself.
Here are the screenshots.
![Screenshot_2024-09-07-11-47-23-94_607c32808e0e5626a9c8a6925b108d16.jpg](https://github.com/user-attachments/assets/fb7a3f7e-e76a-4312-acee-bea35e959c3e)

![Screenshot_2024-09-07-11-42-58-96_bf5286d428c97f865e4b51a5afbaefcd.jpg](https://github.com/user-attachments/assets/452b75c3-c3a4-4850-ab6f-925e6899d83d)

**Comment by IacobIonut01** [comment]
Please check discussion #453 .

As I've said there, the apk size grew a lot because it is an universal apk that contains all the native libraries required to render special formats of images REQUESTED to be supported in the app. The only way around is to ship splitted apks that contains those libraries only for the specific ABI architecture.

Another step you can take is to download both apks and analyse them to get back the same conclusion - new image decoding libraries.

**Comment by rafnov** [comment]
Ssso... A simple and lightwieight gallery - as described - is supposed do be now over 120 MB...? Fossify grew lately, but still not that huge. Check youself their app history...

**Comment by IacobIonut01** [comment]
> Ssso... A simple and lightwieight gallery - as described - is supposed do be now over 120 MB...? Fossify grew lately, but still not that huge. Check youself their app history...

Very much so if the community wants specific support for some specific media formats like JXL and better HEIF/AVIF support, those libraries that adds the support are pure native decoders (C++) and they take space as well, the 120MB size is, as you can see for yourself, the sum of all those decoders for each ABI. Now in nightly and starting with the next release as well, you can download the apk for your specific architecture, reducing the app size significantly to as low as 32MBs

**Comment by rafnov** [comment]
I will check it for sure, as there are no nice & free gallery app except yours and from Fossify (which occured having nasty signigicant bug in loading files).

**Comment by rafnov** [comment]
@Cwpute, may I open?

**Comment by Cwpute** [comment]
I don't understand your question, and i don't see any green Open button

**Comment by rafnov** [comment]
@Cwpute, I've seen one maybe because I was using 3rd party github client (Octodroid). Nevermind.

**Comment by secretmango** [comment]
@rafnov v8a is 64bit, v7a is 32bit

You should always use v8a if available

**Comment by rafnov** [comment]
4.0 is 300 MB now... 😬😮‍💨🤯

**Comment by IacobIonut01** [comment]
> 4.0 is 300 MB now... 😬😮‍💨🤯

For now, I am working on making models downloadable and completely optional
