### ISSUE TITLE
3.0.0 is a disaster movie on my device

### ISSUE THREAD

**Issue by serrq** [IacobIonut01/Gallery#472]
Android 14
Gallery nomap 3.0.0-30033
OnePlus CPH2399

No way to enlarge the boxes.
The 2.1.2 ran smoothly.

**Comment by IacobIonut01** [comment]
Take the time to properly fill an issue form.

If you're referring to the albums column size, you can use gestures to increase or decrease the number.
Currently it tries to find the right one based on `calculateWindowSizeClass` from material3

**Comment by IacobIonut01** [comment]
> Yes, gestures.
> 
> I believed it was a bug, sorry dev. You are terribly right.

No problem, later on will be a visible way to change the grid size without relying on gestures
