### ISSUE TITLE
[BUG] Crash on open after upgrading from 30024 to latest build

### ISSUE THREAD

**Issue by namesarebloat** [IacobIonut01/Gallery#474]
**Describe the bug**
App crashes on open after upgradung from 30024 to 30033, 30101, or the latest github action build.

**To Reproduce**
1. Have 30024 installed
2. Install any newer version
3. Click in app icon
4. It crashes

**Expected behavior**
It shouldn't crash

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Poco X3
 - OS: LOS 21/Android 14
 - Version 30024+

**Additional context**
Attached log
[crash.log](https://github.com/user-attachments/files/16918561/crash.log)

**Comment by IacobIonut01** [comment]
> Maybe not that big of a deal, because 30024 was just a nightly and going from 21204 to the latest github action build works without problem.

Yeah, the problem was that I validated the version upgrade only from official release, not from latest nightly release
