### ISSUE TITLE
[Enhancement] Add Version Number in File Name on Released Page 

### ISSUE THREAD

**Issue by itspdp** [IacobIonut01/Gallery#48]
All the Released Files have "Gallery.apk" name.
But you can append version number after that.
For example -
"Gallery 1.0.1.apk"
"Gallery 1.04.apk"
Etc

So that when I/we will download a new update, it gives us proper info about the File with just reading the file-name.
(Currently it goes like "Gallery.apk" , "Gallery(1).apk", "Gallery (2).apk" etc.

**Comment by IacobIonut01** [comment]
This is more of a non-issue, but it's nothing from my side to make sure the filename to include the release version. Thanks for the suggestion and the next releases will include the version as well!
