### ISSUE TITLE
[BUG] gallery crash when opening photo from file manager

### ISSUE THREAD

**Issue by krzemyczek** [IacobIonut01/Gallery#488]
**Describe the bug**
when I try opening any photo from file manager, app crash

**To Reproduce**
1. Go to file manager app
2. Click on any photo you want to open
3. open via gallery app

**Expected behavior**
App should allow preview of the photo you selected

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 6a]
 - OS: [GrapheneOS 14 (AP2A.240905.003.F1)]
 - Version [e.g. 3.0.0]

**Comment by IacobIonut01** [comment]
Could not reproduce. Make sure you're using the latest nightly before submitting any issue report

**Comment by krzemyczek** [comment]
i checked with nighty version, it works. I'll remamber to use night version next time!
