### ISSUE TITLE
[BUG] Cannot ignore folders/galleries after update to 3.0.0

### ISSUE THREAD

**Issue by potatopplking** [IacobIonut01/Gallery#489]
Hello! First of all I really like your app, it is exactly what I need. I use it daily for quite some time. Thank you for this project! However updating to 3.0.0 broke crucial feature for me - ignoring certain folders.

**Describe the bug**

In previous version I used (2.1.2) there was an option to ignore a folder. Now in 3.0.0 it seems like it's only possible to ignore albums. There are many photos (from e.g. WhatsApp folder) which are not part of any album, so they cannot be ignored at all. Please see attached screenshot - this setting used to work on 2.1.2.

So my actual photos are drowned out by hundreds of WhatsApp images.

**To Reproduce**

Have images on the phone which are not in any album.

**Expected behavior**

A possibility to ignore a folder, just like it was in previous version. Or create automatically album from all folders, so that those folders can be ignored.

**Screenshots**

A configuration of ignored folders which used to work on 2.1.2:

![image](https://github.com/user-attachments/assets/11b72f5e-30d2-4de8-a4d9-a563f2f92d1f)

**Smartphone**
 - Device: Fairphone 4
 - OS: Android 13
 - Version 3.0.0

Thanks a lot!

**Comment by IacobIonut01** [comment]
If a photo is shown in the gallery, then it's part of an album.
You should create a regex pattern that matches all the albums you want to cover in one entry. About creating one, please consult online tools.

**Comment by potatopplking** [comment]
Seems like there's something a bit weird going on with the albums - before I applied the regex there were only 3 albums, now there's 7 (but still not the WhatsApp ones). Maybe there's some kind of indexing going on in the background? Anyway, it doesn't matter, regex worked well. Nice feature! Sorry to needlessly trouble you and thank you for the support. Have a nice day!
