### ISSUE TITLE
[BUG] Unable to display large images clearly

### ISSUE THREAD

**Issue by sojuo** [IacobIonut01/Gallery#491]
## [Delete before submission] Please use and reproduce the bug on the latest build from Github Actions (Artifacts)
**Describe the bug**
After stitching several small images into a larger one, Gallery is unable to display the resulting image clearly.

**To Reproduce**
1. Stitch several small images together to create a larger image.
2. Unable to Display Large Images Clearly.

**Expected behavior**
Images can be displayed clearly in larger sizes.

**files**
[files.zip](https://github.com/user-attachments/files/17229254/files.zip)
![output](https://files.catbox.moe/0ov481.avif)

**Smartphone (please complete the following information):**
 - Device: Redmi k40
 - OS: MIUI 13
 - Version MIUI-V13.0.7.0.SKHCNXM

**Additional context**
You can see others information in here→https://github.com/T8RIN/ImageToolbox/issues/1379#issue-2561567827

**Comment by IacobIonut01** [comment]
Issue has been escalated to the zoomimage library https://github.com/panpf/zoomimage/issues/44

**Comment by IacobIonut01** [comment]
"For AVIF format, decoding through BitmapFactory is supported since Android 12, but BitmapRegionDecoder, which relies on subsampling, still does not support avif format until the current Android 15

Until the latest Android 15 version, BitmapFactory and BitmapRegionDecoder do not support TIFF and DNG format images.

I am also actively looking for third-party libraries to support more image formats. If you also have suitable library recommendations, please let me know"

**Comment by sojuo** [comment]
> "For AVIF format, decoding through BitmapFactory is supported since Android 12, but BitmapRegionDecoder, which relies on subsampling, still does not support avif format until the current Android 15
> 
> Until the latest Android 15 version, BitmapFactory and BitmapRegionDecoder do not support TIFF and DNG format images.
> 
> I am also actively looking for third-party libraries to support more image formats. If you also have suitable library recommendations, please let me know"

Uploading AVIF images to an image hosting service allows for clear viewing in browsers like Mull.

**Comment by IacobIonut01** [comment]
> > "For AVIF format, decoding through BitmapFactory is supported since Android 12, but BitmapRegionDecoder, which relies on subsampling, still does not support avif format until the current Android 15
> > Until the latest Android 15 version, BitmapFactory and BitmapRegionDecoder do not support TIFF and DNG format images.
> > I am also actively looking for third-party libraries to support more image formats. If you also have suitable library recommendations, please let me know"
> 
> Uploading AVIF images to an image hosting service allows for clear viewing in browsers like Mull.

We are talking about the native and available APIs in the android, you can research for yourself, but currently is not yet possible
