### ISSUE TITLE
[Enhancement] Albums and image previews are tiny

### ISSUE THREAD

**Issue by stpnwf** [IacobIonut01/Gallery#493]
**Is your feature request related to a problem? Please describe.**
New update made using this app a bad experience. Album and image previews are tiny and that can't be configured in settings. Not to mention that to me this looks very ugly now.

**Describe the solution you'd like**
The ability to choose how many albums and images are shown per row in the album view, inside the album view and in the timeline should be available in settings. 4 and 6 are way too many. Should be 2 and 3-4.

**Describe alternatives you've considered**
Revert to what it used to be like an update or two ago, it looked so much better. Now it is very hard to use the app.

**Additional context**
What is the point of having 4 albums per row when you can only read 3 letters from its name? Is this a bug?

Having 6 images per row in the preview is horrible for visibility. I am trying to find a screenshot of text I took a while ago and bc it is so tiny I get no clue from the preview. Now I have to look at one by one to find it, which is very annoying. Ppl should be able to configure this in settings.

Really loving this all otherwise

## Screenshots

![Screenshot_20241009-215551_1](https://github.com/user-attachments/assets/3c08465a-47fb-47f8-971c-6424b9e60a63)
![Screenshot_20241009-215441_1](https://github.com/user-attachments/assets/5aa165d8-a3f2-4055-bb0d-3a9cd42cbe05)

**Comment by IacobIonut01** [comment]
Use gestures to zoom in and out to change the grid column sizes (on both media and albums)

**Comment by IacobIonut01** [comment]
> Gestures dont work for me somehow. For me it is 4 in a row, while 3 would be preferred
> 
> Gestures do nothinf while working fine in other apps (not the touchscreen)
> 
> Latest Github release, Android 16/GrapheneOS, Pixel 6a

While this is not ideal, you can scroll to a section where you have a small amount of images per grid or when it is showing a big month header, in that empty space you should be able to use it
