### ISSUE TITLE
Enhancement: the ability to hide albums

### ISSUE THREAD

**Issue by ghost** [IacobIonut01/Gallery#5]
Enhancement: the ability to hide albums

**Comment by ldx23** [comment]
Hello @IacobIonut01, are there any updates on this/any eta?

**Comment by IacobIonut01** [comment]
The project was postponed due to my vacation, will be back on track these days

**Comment by IacobIonut01** [comment]
Anything else regarding the requirements for the Vault Setup?

![Setup](https://github.com/IacobIonut01/Gallery/assets/19311643/8aaad877-4c34-4988-b96b-08fc389f2e1a)
![Setup Error](https://github.com/IacobIonut01/Gallery/assets/19311643/537476af-c9f1-41e4-8a33-9732a8513635)

**Comment by IacobIonut01** [comment]
I was thinking of multiple vaults support (independent encryption), so each of them will have only a timeline screen.

**Comment by ldx23** [comment]
That would be cool but folders are good for organization (i can have 50 folders but having 50 different passwords for different vaults wont make sense)
would it be hard to implement?

i can try helping, but i'm having some problems with the android studio setup for this project. do i need the beta version of android studio?

**Comment by IacobIonut01** [comment]
The vaults will use a singular method of auth (device security, so could be your lockscreen password or biometrics), only the actual encryption key is different, but I'll see about making a singular vault with folder support.

Use the latest android studio canary

**Comment by ViktorKahu** [comment]
How are we going with this? Should I close the issue as "not planned"?

**Comment by IacobIonut01** [comment]
It is indeed planned, but it takes a bit to complete it since there're quite a lot of factors to consider and I'm also not working only on this feature
