### ISSUE TITLE
Improve app icon

### ISSUE THREAD

**Issue by T8RIN** [IacobIonut01/Gallery#50]
Hi, this app is nice, but Is it possible to make the app icon more materialistic?

**Comment by IacobIonut01** [comment]
The current icon is already made with Material 3 guidelines in mind
![image](https://user-images.githubusercontent.com/19311643/235291978-eaebb580-e769-44c9-a628-b8d0907c5354.png)


But if you have any other ideas, I am open to change.

Any recommendation is welcomed as an svg/figma link

**Comment by T8RIN** [comment]
I'm meaning something like this 

![image](https://user-images.githubusercontent.com/52178347/235292412-079b03e9-cfe0-41aa-8ab6-3c7e0e0b5405.png)

i.e. vfking icon more flat? Without too much colors on it itself? what do you think about it?

**Comment by T8RIN** [comment]
Or like it is made in my own app - [ImageResizer](https://github.com/t8rin/imageresizer)

**Comment by T8RIN** [comment]
In my opinion current icon had too thin borders, so it looks not suitable (i'dont know another word) across other icons

**Comment by IacobIonut01** [comment]
> I'm meaning something like this
> 
> ![image](https://user-images.githubusercontent.com/52178347/235292412-079b03e9-cfe0-41aa-8ab6-3c7e0e0b5405.png) https://www.vectorstock.com/royalty-free-vector/gallery-icon-vector-21679672
> 
> i.e. vfking icon more flat? Without too much colors on it itself? what do you think about it?

I'm not a fan of monochrome icons unless they are system themed.

**Comment by IacobIonut01** [comment]
> In my opinion current icon had too thin borders, so it looks not suitable (i'dont know another word) across other icons

You mean the borders from the monochrome icon?

**Comment by IacobIonut01** [comment]
![image](https://user-images.githubusercontent.com/19311643/235292629-a343e09c-32a6-42e8-aaea-49a0e659e50e.png)
something like this

**Comment by T8RIN** [comment]
Yup, and making the icon more square like, google recommends icons to be 24*24, so it will be symmetric, and making corners of  hills more rounded

**Comment by T8RIN** [comment]
> > I'm meaning something like this
> > ![image](https://user-images.githubusercontent.com/52178347/235292412-079b03e9-cfe0-41aa-8ab6-3c7e0e0b5405.png) https://www.vectorstock.com/royalty-free-vector/gallery-icon-vector-21679672
> > i.e. vfking icon more flat? Without too much colors on it itself? what do you think about it?
> 
> I'm not a fan of monochrome icons unless they are system themed.

What is something like this? (one sec, i will upload it now)

**Comment by T8RIN** [comment]
![sketch-1682758522333.png](https://user-images.githubusercontent.com/52178347/235294222-be245dc4-e870-4a68-9445-391362f4cde8.png)

**Comment by T8RIN** [comment]
![sketch-1682758522333.png](https://user-images.githubusercontent.com/52178347/235294222-be245dc4-e870-4a68-9445-391362f4cde8.png)

Your icon is good too, but it would be better in my opinion, if you make it more squareic and round hills :)

**Comment by T8RIN** [comment]
![Screenshot_20230429-174124_Chrome.png](https://user-images.githubusercontent.com/52178347/235308642-64e3b7a1-ed45-42e8-a9fd-07a8cdc4bdb4.png)

And also changed the monochrome icon too

**Comment by T8RIN** [comment]
Background is white as it was

**Comment by T8RIN** [comment]
![image](https://user-images.githubusercontent.com/52178347/235309052-f65da444-fd6a-463a-a6b3-9a00c5cd1168.png)
![image](https://user-images.githubusercontent.com/52178347/235309064-b16e7c35-b19c-44ad-b328-fe901b45725a.png)

**Comment by IacobIonut01** [comment]
Thanks a lot, I like it. I'll merge your PR asap
