### ISSUE TITLE
[BUG] Scope Control Issue in 'Ignored' Feature with Regex Pattern

### ISSUE THREAD

**Issue by RejectVanity** [IacobIonut01/Gallery#511]
**Describe the bug**
The current behavior is that when selecting "Albums" or "Timeline" in the "Ignored" feature while using the "Regex Pattern" mode, any matched content disappears from both pages. This behavior is inconsistent with the intended functionality, as it hides the ignored content on all pages rather than only on the specified page.

**To Reproduce**

**Expected behavior**
When "Albums" is selected in the "Ignored" feature, content matched by the regex pattern should only be hidden on the "Albums" page while remaining visible on the "Timeline" page. Similarly, if "Timeline" is selected, matched content should only be hidden on the "Timeline" page, while still being visible on the "Albums" page.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Remi K40s (Munch)
 - Android 14
 - Version HyperOS 1.0

**Additional context**
This feedback text was translated (Chinese to English) using translation software.  I apologize for any inaccuracies.

**Comment by IacobIonut01** [comment]
Fixed in the latest nightly
