### ISSUE TITLE
Remove DependencyInfoBlock for F-Droid

### ISSUE THREAD

**Issue by linsui** [IacobIonut01/Gallery#512]
**Describe the bug**
We find that there is a `DependencyInfoBlock` in your apk. It's a [Frosting](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) block in the signing block. It's added by AGP and signed by Google's public key so it can't be read by anyone else except Google.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 6]
 - OS: [e.g. Android 14]
 - Version [e.g. 1.1.0]

**Additional context**

**Comment by linsui** [comment]
And could you please change the version code scheme for every abi to 300331, 300332... so that we can publish splitted apks?

**Comment by IacobIonut01** [comment]
> **Describe the bug** We find that there is a `DependencyInfoBlock` in your apk. It's a [Frosting](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) block in the signing block. It's added by AGP and signed by Google's public key so it can't be read by anyone else except Google.
> 
> Could you please disable it with the following code?
> 
> ```
> android {
>     dependenciesInfo {
>         // Disables dependency metadata when building APKs.
>         includeInApk = false
>         // Disables dependency metadata when building Android App Bundles.
>         includeInBundle = false
>     }
> }
> ```
> 
> Thanks!
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Google Pixel 6]
> * OS: [e.g. Android 14]
> * Version [e.g. 1.1.0]
> 
> **Additional context** Add any other context about the problem here.

Will this impact in any way the Google Play release variant?

**Comment by linsui** [comment]
I don't know. Google Play and this block are opaque. I never hear about such cases so I thought it's OK. :)

**Comment by linsui** [comment]
Thanks!
