### ISSUE TITLE
[BUG] App crashes when viewing albums ignored in timeline

### ISSUE THREAD

**Issue by reifmaxi** [IacobIonut01/Gallery#513]
**Describe the bug**
A folder only ignored in the main Timeline is still shown in the Albums tab (as expected) but keeps Gallery stopping when clicking on it.

**To Reproduce**
1. Click on the bottom right tab icon and further on "Ignored" to enter the "Ignored Albums" menu.
2. At "Where should be ignored" choose "Timeline"; at "Who should be ignored" choose "Selection".
3. Pick some test folder, e.g. Downloads, and apply the confirmation.
4. Now the pictures within the chosen folder are not shown in the main Timeline anymore, while the chosen folder is still shown in the Albums tab (as expected).
5. However, clicking on the folder crashes the app.

**Expected behavior**
Gallery should still be able to open the folder via the Albums tab and allow the user to view the pictures within.

**Smartphone:**
 - Device: Fairphone 5
 - OS: Android 14
 - Version 3.0.0

**Additional context:**
Also, selecting a picture withing the ignored folder in another app to view it with Gallery doesn't work.

**Comment by IacobIonut01** [comment]
Good catch
