### ISSUE TITLE
[Proposal] Add Monero (XMR) as a donation option

### ISSUE THREAD

**Issue by TheFuzzStone** [IacobIonut01/Gallery#519]
Hey. 

I want to support you and donate some XMR.

Choose your wallet here: https://www.getmonero.org/downloads/

Ping me please with @ when you add a Monero wallet address. 

A very cool Gallery app! 
Thanks.

**Comment by IacobIonut01** [comment]
@TheFuzzStone 

`48JMiDR8mZiEis8V5pWtxv3r121K6fqqZfhajiewCbff27GnucdyLfkQ12Fr6ZM1eR9Botdu3Rx1bidmHyLTZBWnJ4AJKot`

**Comment by TheFuzzStone** [comment]
@IacobIonut01, done. Thanks for the cool app. :)
