### ISSUE TITLE
The app size issue in fdroid is still not solved, but the issue was closed .

### ISSUE THREAD

**Issue by ghost** [IacobIonut01/Gallery#521]
so making another one incase it was a mistake/misunderstanding . The app is now almost 4 times bigger than actually needed which might turn of a lot of users and have issues with people running older/weaker devices and custom roms . This will make the app more accessible .

**Comment by cyber-psych** [comment]
fdroid automatically updates and suggest the apk suitable for the user uf that's what you mean . You can check fennec and VLC which are two apps i use that does this .

**Comment by Cwpute** [comment]
So as i understand, the reason we have big apk on Fdroid is because only the universal apk was sent to them by the maintainers of Gallery, right ?

**Comment by IacobIonut01** [comment]
> So as i understand, the reason we have big apk on Fdroid is because only the universal apk was sent to them by the maintainers of Gallery, right ?

There's no apk sent, they compile themselves

**Comment by IacobIonut01** [comment]
> > There's no apk sent, they compile themselves
> 
> 
> Not a dev, but there is an option for the developers to supply split architecture apps . There are multiple apps on fdroid with split architectures, i would know cause i use them, i do think there is some work to be done in the start by the dev and after that fdroid updates automatically like they do now without much input by the dev .
> 
> 

There's an open issue regarding adding support for split apks in fdroid by adding an increment to the end of the versioncode

**Comment by cyber-psych** [comment]
oh, can you link me that issue ? i opened this cause i couldn't find one but if there aldready is one i prolly should close this yea ?

**Comment by Cwpute** [comment]
@cyber-psych they are referring to an issue on Fdroid's repository about split apks, not in Gallery's repository !

This is most likel the issue we're talking about: https://gitlab.com/fdroid/fdroidserver/-/issues/82
If you know anybody who could help with this, please come forth and introduce them to this issue.

**Comment by cyber-psych** [comment]
i personally don't kbow anyone, i am not a dev either if i were i would've loved to help out

**Comment by cyber-psych** [comment]
i personally don't know anyone, i am not a dev either if i were i would've loved to help out

**Comment by cyber-psych** [comment]
@IacobIonut01 what are your thoughts ? do you intend to support split apks on fdroid in near future ?
