### ISSUE TITLE
[Bug] Maximum zooming of the images

### ISSUE THREAD

**Issue by jamal2362** [IacobIonut01/Gallery#53]
Hey 👋,

I noticed that when zooming an image to the maximum, it is unfortunately no longer possible to unzoom it with 2 fingers. It only works to double tap the display to completely unzoom the image.

**Comment by IacobIonut01** [comment]
It's not really a consistent bug, sometimes works sometimes doesn't. 100% of the times works if you unzoom vertically with two fingers, but still a bug, I'll try to improve the gestures even more. Thanks!

**Comment by IacobIonut01** [comment]
Should be fixed in 1.1 beta release
