### ISSUE TITLE
[Enhancement] Reduce the Fade In/Fade Out Animation Time for Viewer UI elements

### ISSUE THREAD

**Issue by thisisartman** [IacobIonut01/Gallery#535]
**Is your feature request related to a problem? Please describe.**
Currently, the UI elements take almost an entire second to appear and then vanish when the screen is tapped. This makes taking actions on the images delayed and sluggish. 

**Describe the solution you'd like**
Reducing the duration of the animation to somewhere between 300ms - 500ms would be awesome. 

**Describe alternatives you've considered**
The only alternative at present is to wait that entire duration for the UI elements to appear or disappear. 

**Additional context**
Adding screen recordings from Google Photos & the Fossify Gallery app as references.

Google Photos:
https://github.com/user-attachments/assets/a1c81c36-9a10-4e64-9e06-f85f302cc4b5

Fossify Gallery:
https://github.com/user-attachments/assets/501e6435-c31c-4348-8894-7d9c38a2d3de

**Comment by IacobIonut01** [comment]
Fixed in the latest release
