### ISSUE TITLE
[BUG] Image has weird blob around it when entering Edit UI. 

### ISSUE THREAD

**Issue by thisisartman** [IacobIonut01/Gallery#537]
**Describe the bug**
When you open the edit UI, if an image is not filling the screen, then theres a weird blob that fills that space.

**To Reproduce**
1. Go to any image that doesn't fill the screen. 
2. Tap the edit button. 
3. Voila! 

**Expected behavior**
Just the image without any blobs around it. 

**Screenshots**
![Screenshot_20241120-050608_Gallery.png](https://github.com/user-attachments/assets/307bf950-9498-40f1-850e-280947a5d18d)

![Screenshot_20241120-045508_Gallery.png](https://github.com/user-attachments/assets/295aa31c-54a4-496a-9530-5fb96d711715)

**Smartphone (please complete the following information):**
 - Device: Poco F4 5G
 - OS: crDroid 10.9 (Android 14)
 - Version 3.0.1

**Comment by IacobIonut01** [comment]
it is intended
