### ISSUE TITLE
[Bug] Bottom sheet has a visual issue at the edge

### ISSUE THREAD

**Issue by jamal2362** [IacobIonut01/Gallery#54]
Hey 👋,

There is a visual error at the edge in the bottom sheet as shown in the picture. You can easily see through it. On the left side it is correct.

![Screenshot_20230428-231224~2](https://user-images.githubusercontent.com/15986930/235255613-b7aa9482-01ab-4694-b2f3-db6e4cc2c256.png)

**Comment by IacobIonut01** [comment]
Yeah, I am aware of the 'bugs' that the Material3 Modal Bottom Sheet currently has. At this particular moment I can't do anything but to wait for the material3 library to fix these issues. The other solution would be to move the media details to a complete different screen, like Gallery Go does

**Comment by jamal2362** [comment]
Hello,
That's right. I hadn't thought of that at all. 😄
Then we just wait for a fix for the library.

**Comment by IacobIonut01** [comment]
Waiting for Material3 Compose library to fix the issue
