### ISSUE TITLE
[BUG] Cannot run image classification

### ISSUE THREAD

**Issue by BoBkiNN** [IacobIonut01/Gallery#554]
**Describe the bug**
When i click "categorise your media", "scanning media..." progress bar displays for about 0.1 seconds and then disappears and then nothing happens

**To Reproduce**
1. Go to library
2. Click "Categorise your media" to open Categories screen 
3. Click "Categorise your media" 

**Expected behavior**
I will see how my media is categorized

**Screenshots**
(Taken while spamming button)
![image](https://github.com/user-attachments/assets/6a1f01c9-2907-4496-b6bf-dc13eeac405b)

**Smartphone:**
 - Device: TECNO Pova Neo 2
 - OS: Android 12 (api 31)
 - Version: 3.1.0 (310204)

**Additional context**
When run with android studio, there are debug log messages about it:
![studio64_IwtNacdyDx](https://github.com/user-attachments/assets/569752d4-f4b7-4fda-ad8e-840ace6d9093)

**Comment by IacobIonut01** [comment]
Re-open the app, and check logs for `Database is not up to date. Updating to version` or `Database is up to date`

**Comment by BoBkiNN** [comment]
![studio64_5kBiPzQitP](https://github.com/user-attachments/assets/11a95c30-d3fa-49ef-bdea-d66a38e5d412)
This logs are existing

**Comment by IacobIonut01** [comment]
Make sure you have full media permissions granted

**Comment by BoBkiNN** [comment]
All permissions is granted

**Comment by BoBkiNN** [comment]
It fixed when i took screenshot to change media store generation. Weird
