### ISSUE TITLE
F-Droid autoupdate for splitted abis doesn't work with the tag name

### ISSUE THREAD

**Issue by linsui** [IacobIonut01/Gallery#556]
F-Droid can only calculate the url from the version code and version name. But the tag name has 31020 which is not the version code (e.g. 310202). Could you please remove it from the tag name and use the version name only? Thanks!

**Comment by IacobIonut01** [comment]
Updated tag to [3.1.0](https://github.com/IacobIonut01/Gallery/releases/tag/3.1.0)

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
Hi, this also happens on the 3.1.1 tag. Could you pleae also fix it?

**Comment by IacobIonut01** [comment]
> Hi, this also happens on the 3.1.1 tag. Could you pleae also fix it?

Done, I've forgotten to update the CI so this won't happen again. Thanks

**Comment by linsui** [comment]
Thanks!
