### ISSUE TITLE
[BUG] Renaming a photo causes it to drop from the media database, it also changes the file timestamp

### ISSUE THREAD

**Issue by bw22** [IacobIonut01/Gallery#557]
After a rename, the picture immediately disappeared from the gallery and is not shown by any other media gallery app either. The file itself is fine and if a file explorer app is used to rename it again then it shows back up.

Secondary issue, renaming the file is also modifying the file's creation timestamp. This isn't necessarily wrong but is different from other gallery tools.. it is useful to preserve the file's other meta data when just renaming.

**To Reproduce**
1. Pull up the information for a picture
2. Click on Edit by the label and give it a new name
3. The picture immediately closes and is not shown in the gallery (or other gallery apps )

**Expected behavior**
Not that. 😉

**Screenshots**

**Smartphone**
Confirmed on 2 devices:
 - Moto g 5g stylus 2024, running Android 14
 - Samsung S20 5g FE, running Android 13
 - Tested Gallery app version 3.0.1 which is currently in F-Droid

Thanks! I'm impressed with your app's many details and would love to help. I'm also a developer so can do any testing or provide any other details you like.

**Comment by IacobIonut01** [comment]
Confirmed.
