### ISSUE TITLE
[Enhancement] Translate application into Hindi language

### ISSUE THREAD

**Issue by rahirwareic** [IacobIonut01/Gallery#558]
Please use the latest build from Github Actions (Artifacts)

**Is your feature request related to a problem? Please describe.**
No, it is a new feature, I can translate this application into the Hindi Language

**Describe the solution you'd like**
I am an Android Developer I can translate this application into Hindi language, so we can increase the user of this application.

**Describe alternatives you've considered**
English is a alternative language, but if we can translate this into Hindi language it will be helpful for the local people those don't know English, there default language of the Phone is Hindi. It would be a good user experience.

**Additional context**
Add a new localization of Hindi.

**Comment by IacobIonut01** [comment]
Updated the crowdin supported languages, you can start translation from there
