### ISSUE TITLE
[BUG] videos don't play in the last two versions of the app

### ISSUE THREAD

**Issue by fallsdevil** [IacobIonut01/Gallery#559]
**Describe the bug**
When opening the videos, they don't play, I don't know what the pattern of the problem is, but one video or another plays normally, and the others don't (which is the majority that don't work).

**To Reproduce**
1. Go to 'for the video'
2. Click on 'on the play button or in the time bar'
3. the video goes full screen but nothing happens.
4. See error (The progress bar is also empty and the time is: 00:00)

**Expected behavior**
that the videos worked

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy A10s
 - OS: Android 11
 - Version: 3.1.0 (but in the previous version too)

**Additional context**
In the previous version, the videos always stopped after a few msec, but when I dragged it to the side and a part of the other video appeared, it started working again and the video next to it always went without freezing.

**Comment by IacobIonut01** [comment]
The videos are working fine here, take a full logcat while trying to play videos.

**Comment by mon-jai** [comment]
@IacobIonut01 I encountered the same problem on a Pixel 6a running Android 15 QPR2 BP11.241025.006 (a beta release).

The bug appears to be situational, depending on the video file. Some videos play without any issues and always stay that way, while for others, it seems random which of the following problems occurs:

- The audio plays normally, but the video gets stuck on the first frame
- Neither the audio nor the video plays

**Comment by mon-jai** [comment]
For videos that won't play (yeah you see the taps):

https://github.com/user-attachments/assets/dd3173c4-f8f0-424a-8443-b33f89acc748

**Comment by fallsdevil** [comment]
> Para vídeos que não serão reproduzidos (sim, você viu o toque no botão play):
> 
>  tela-20241216-035643.mp4.2.mp4

yes, that's exactly what happens, and in my case the audio doesn't even come out, tomorrow I tried to send the log...

**Comment by fallsdevil** [comment]
I don't know how to generate the log to try to help, I looked in the app settings and couldn't find it :(

**Comment by IacobIonut01** [comment]
> I don't know how to generate the log to try to help, I looked in the app settings and couldn't find it :(

Google: How to take a logcat with adb

**Comment by fallsdevil** [comment]
> Google: How to take a logcat with adb

I managed to generate it, I tested it as follows:
- I opened the video and clicked play 
- then I dragged it to the side and pressed play and the video played, but I couldn't pause it. 

[logs.txt](https://github.com/user-attachments/files/18466204/logs.txt)

I don't understand how it works, but I quickly looked at the file and apparently the errors are named "audio" something, maybe this will help to optimize the search for the error...

**Comment by IacobIonut01** [comment]
If now it plays well, then could be a totally different problem after all, the logs doesn't contain anything relevant to the video issues.

**Comment by fallsdevil** [comment]
It's a shame it was irrelevant, but yes it only works when I open another video and then come back, anyway, I'll wait.
