### ISSUE TITLE
[Feature Request] Deletion confirmation when emptying the trash

### ISSUE THREAD

**Issue by jamal2362** [IacobIonut01/Gallery#56]
Hey 👋,

It would be nice if there is a deletion confirmation (dialog) when emptying the trash. So as a last warning.

This prevents the trash from being deleted by mistake.

**Comment by IacobIonut01** [comment]
These confirmations exists if the 'Manage media' permission is not granted, but for the cases where it's granted, I'll make sure a confirmation dialog will be added for trash

**Comment by IacobIonut01** [comment]
Available in HEAD
