### ISSUE TITLE
Ability to view videos and photos on flash drives and sd cards

### ISSUE THREAD

**Issue by Wjxfi** [IacobIonut01/Gallery#58]

**Comment by IacobIonut01** [comment]
By default any media that is scanned by MediaStoreScanner should be visible in the app. Viewing media from other storage spaces other than the ones available through the MediaStoreScanner would require a separate implementation, but I'll try to figure out a workaround for this issue.

**Comment by IacobIonut01** [comment]
As long as media is visible in other Gallery Apps (system scanned the media and has been indexed), it will be visible in this app as well.
