### ISSUE TITLE
Bug: Zooming photos also zooms the black frames on the photo viewer. See screenshot.

### ISSUE THREAD

**Issue by sledgehammer0019** [IacobIonut01/Gallery#63]
![Uploading Screenshot_20230502-121726_Gallery.png…]()

**Comment by IacobIonut01** [comment]
Hi, thanks for opening the ticket.

I am already aware of the issue and I will try to fix it in the 1.1 release

**Comment by IacobIonut01** [comment]
Fixed in 1.1 beta release
