### ISSUE TITLE
[Bug] Crash in albums

### ISSUE THREAD

**Issue by T8RIN** [IacobIonut01/Gallery#65]
If you open the app, and then immediately tap to the albums, then you will have a crash

https://user-images.githubusercontent.com/52178347/236134986-b7080250-2c4d-4973-9a47-91464be5b44b.mp4

Android 13 PE

**Comment by IacobIonut01** [comment]
Fixed on HEAD

**Comment by IacobIonut01** [comment]
After changed from Glide with preloader to coil for Album screen it's gone, try to build from Git Actions (latest) and lmk

**Comment by T8RIN** [comment]
Got it :)
