### ISSUE TITLE
[Feature request] add support for older android versions

### ISSUE THREAD

**Issue by Sukii23** [IacobIonut01/Gallery#66]
having support only for android 11 and 13 is extremely limited. Many users still use android 9, 10 or others..

**Comment by IacobIonut01** [comment]
The app is supported on android 11+ for API limitation reasons.

In order for the app to support lower android versions it must suffer from heavy modifications on the API access level (Media access) and features like trash or favorites won't be supported anymore (unless a custom implementation of it is made, which I don't want to nor have the time to do).

Other developers or skilled users can give it a try to support lower SDKs, but from my side I will not

**Comment by franco27** [comment]
I agree with you. It's extremely limited. I can't enjoy this app
