### ISSUE TITLE
SVGs broken in latest release

### ISSUE THREAD

**Issue by julianfairfax** [IacobIonut01/Gallery#67]
SVG viewing is broken in the latest release.

![Screenshot_20230507-181743](https://user-images.githubusercontent.com/43753131/236689585-c168680a-bd68-4853-b484-c271a780d5a7.png)
![Screenshot_20230507-181750](https://user-images.githubusercontent.com/43753131/236689587-41348a8d-2bdf-4060-95c4-85b4ffa22615.png)

**Comment by IacobIonut01** [comment]
SVG Support is still experimental, some svgs might be supported, some might not.

**Comment by IacobIonut01** [comment]
SVG Support is based on the library used [here](https://github.com/IacobIonut01/Gallery/blob/a1248ee81ad0bd30fb2c58014e9e1121dc0ee198/app/build.gradle.kts#LL180C45-L180C45)

So, between releases I did not touch any svg implementation, but if this issue still persists over any further release, I'll consider moving from depending on an external library for the implementation

**Comment by IacobIonut01** [comment]
Has been fixed.
