### ISSUE TITLE
Improve animation when switching between images

### ISSUE THREAD

**Issue by Krintni** [IacobIonut01/Gallery#68]
When you switch between images the animation isn't so smooth and there's room for improvement. Here's a screen recording that compares Google Photos and Gallery to show you what I mean:

https://github.com/IacobIonut01/Gallery/assets/132835834/cb3d13ce-1299-4707-a8b7-96f360b89b6e

First I'm in Google Photos and then I switch to Gallery and as you can probably see the animation in Gallery is not as smooth as in Google Photos.

**Comment by IacobIonut01** [comment]
High animation speed while low velocity swiping is intentional, there's no jitter or issues while scrolling (aka it's smooth, just faster)

**Comment by Krintni** [comment]
Understood. Then what I meant is that the animation speed is a little bit too high. When low velocity swiping the animation is pretty good, but when swiping normally, for example when I swipe from one to another image, the animation seems a little off-putting compared to other Gallery apps.

**Comment by IacobIonut01** [comment]
After some research I've found out that this issue is consistent with Google's impl of HorizontalPager in Compose. The fix is currently depending on them
