### ISSUE TITLE
[enhancement] Some Suggestions and Bug Reports

### ISSUE THREAD

**Issue by itspdp** [IacobIonut01/Gallery#72]
**1) Going BACK after viewing a searched File**
File Search needs improvement (which you might know) but When we click on a file from the search results to view it.
And then when we click BACK to go back to Previous page (which is the search results page), it doesn't do that and goes back to the Homepage.

**2) Copy File Name/Path from Description Menu.**
Tap OR Long Tap to Copy File Name(Lable) and Path from The Description Menu.
Also Combine Lable and File Path option, as File Path can also contains the File Name.

**3) Add Rename File Option**

**Comment by IacobIonut01** [comment]
1. The behavior was on purpose. But sure I can make it so it returns to the search screen.
2. This is already available - long press to copy
3. In progress

**Comment by IacobIonut01** [comment]
1. Also yeah, the search is still wip. It's going to have better date recognition and content search

**Comment by itspdp** [comment]
```
2. This is already available - long press to copy
```
Yes, sorry, it's working. But I didn't realised.

May be you can add a short Toast like "copied to clipboard" that can notify what just happened (i.e. the Text is copied)

**Comment by IacobIonut01** [comment]
I've actually left it without a toast since on android 13 there's already a clipboard pop-up, but I'll make sure it's added for lower versions

**Comment by itspdp** [comment]
Yepp, thanks 🙏

**Comment by Cyanic76** [comment]
Fyi, I've asked for your 3rd suggestion in #60.

**Comment by itspdp** [comment]
Thanks

**Comment by IacobIonut01** [comment]
All suggestions mentioned in the issue are resolved/fixed.
Closing the issue
