### ISSUE TITLE
[BUG] Sudden full-screen while using the app or while viewing the photo. 

### ISSUE THREAD

**Issue by sledgehammer0019** [IacobIonut01/Gallery#74]
Full screen in this context means the app ignored the camera notch and status bar is hidden for a few seconds. A simple back or scroll will fix it but it will occur again after a few usage.

**Comment by IacobIonut01** [comment]
It's quite an inconsistent bug, I would like to fix it, but first I need to find a way to replicate it properly, I've encountered it myself as well, but I couldn't replicate it consistently to find and fix the issue.

If you find a way to replicate it consistently let me know, it would speed up the process of fixing it
