### ISSUE TITLE
Cutoff at bottom of the screen while viewing photos and videos

### ISSUE THREAD

**Issue by azibazrie07** [IacobIonut01/Gallery#78]
![IMG_20230626_061949](https://github.com/IacobIonut01/Gallery/assets/118100426/9d5f949e-f589-474c-b605-8deab364a04e)
![IMG_20230626_062437](https://github.com/IacobIonut01/Gallery/assets/118100426/43d325f4-dca4-479c-af6c-402c15db9b26)

**Comment by IacobIonut01** [comment]
Fixed here https://github.com/IacobIonut01/Gallery/commit/060fc0ffc39f91d915188df6d9228727ca31cf5e
