### ISSUE TITLE
[BUG] cant open image with kvaesitso

### ISSUE THREAD

**Issue by yant0** [IacobIonut01/Gallery#79]
Extension tried : png, jpg
Image path : sdcard, internal storage
App version : latest
Android 12

https://github.com/IacobIonut01/Gallery/assets/80298071/bd5654ae-b677-4095-9c0f-a6fc176c2471

**Comment by zoroya1** [comment]
I can confirm that it is not working...👍

**Comment by IacobIonut01** [comment]
Let me know if you find any other crashes while opening media from any apps.
